// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: xai/api/v1/types.proto

package ragpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexedChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkNumber   uint32                 `protobuf:"varint,1,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DataHash      []byte                 `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedChunk) Reset() {
	*x = IndexedChunk{}
	mi := &file_xai_api_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedChunk) ProtoMessage() {}

func (x *IndexedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedChunk.ProtoReflect.Descriptor instead.
func (*IndexedChunk) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *IndexedChunk) GetChunkNumber() uint32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *IndexedChunk) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *IndexedChunk) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *IndexedChunk) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

type IndexConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexConfiguration) Reset() {
	*x = IndexConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexConfiguration) ProtoMessage() {}

func (x *IndexConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexConfiguration.ProtoReflect.Descriptor instead.
func (*IndexConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *IndexConfiguration) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type ChunkConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*ChunkConfiguration_CharsConfiguration
	//	*ChunkConfiguration_TokensConfiguration
	Config               isChunkConfiguration_Config `protobuf_oneof:"config"`
	StripWhitespace      bool                        `protobuf:"varint,3,opt,name=strip_whitespace,json=stripWhitespace,proto3" json:"strip_whitespace,omitempty"`
	InjectNameIntoChunks bool                        `protobuf:"varint,4,opt,name=inject_name_into_chunks,json=injectNameIntoChunks,proto3" json:"inject_name_into_chunks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChunkConfiguration) Reset() {
	*x = ChunkConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkConfiguration) ProtoMessage() {}

func (x *ChunkConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkConfiguration.ProtoReflect.Descriptor instead.
func (*ChunkConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkConfiguration) GetConfig() isChunkConfiguration_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ChunkConfiguration) GetCharsConfiguration() *CharsConfiguration {
	if x != nil {
		if x, ok := x.Config.(*ChunkConfiguration_CharsConfiguration); ok {
			return x.CharsConfiguration
		}
	}
	return nil
}

func (x *ChunkConfiguration) GetTokensConfiguration() *TokensConfiguration {
	if x != nil {
		if x, ok := x.Config.(*ChunkConfiguration_TokensConfiguration); ok {
			return x.TokensConfiguration
		}
	}
	return nil
}

func (x *ChunkConfiguration) GetStripWhitespace() bool {
	if x != nil {
		return x.StripWhitespace
	}
	return false
}

func (x *ChunkConfiguration) GetInjectNameIntoChunks() bool {
	if x != nil {
		return x.InjectNameIntoChunks
	}
	return false
}

type isChunkConfiguration_Config interface {
	isChunkConfiguration_Config()
}

type ChunkConfiguration_CharsConfiguration struct {
	CharsConfiguration *CharsConfiguration `protobuf:"bytes,1,opt,name=chars_configuration,json=charsConfiguration,proto3,oneof"`
}

type ChunkConfiguration_TokensConfiguration struct {
	TokensConfiguration *TokensConfiguration `protobuf:"bytes,2,opt,name=tokens_configuration,json=tokensConfiguration,proto3,oneof"`
}

func (*ChunkConfiguration_CharsConfiguration) isChunkConfiguration_Config() {}

func (*ChunkConfiguration_TokensConfiguration) isChunkConfiguration_Config() {}

type CharsConfiguration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxChunkSizeChars int32                  `protobuf:"varint,1,opt,name=max_chunk_size_chars,json=maxChunkSizeChars,proto3" json:"max_chunk_size_chars,omitempty"`
	ChunkOverlapChars int32                  `protobuf:"varint,2,opt,name=chunk_overlap_chars,json=chunkOverlapChars,proto3" json:"chunk_overlap_chars,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CharsConfiguration) Reset() {
	*x = CharsConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharsConfiguration) ProtoMessage() {}

func (x *CharsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharsConfiguration.ProtoReflect.Descriptor instead.
func (*CharsConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *CharsConfiguration) GetMaxChunkSizeChars() int32 {
	if x != nil {
		return x.MaxChunkSizeChars
	}
	return 0
}

func (x *CharsConfiguration) GetChunkOverlapChars() int32 {
	if x != nil {
		return x.ChunkOverlapChars
	}
	return 0
}

type TokensConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxChunkSizeTokens int32                  `protobuf:"varint,1,opt,name=max_chunk_size_tokens,json=maxChunkSizeTokens,proto3" json:"max_chunk_size_tokens,omitempty"`
	ChunkOverlapTokens int32                  `protobuf:"varint,2,opt,name=chunk_overlap_tokens,json=chunkOverlapTokens,proto3" json:"chunk_overlap_tokens,omitempty"`
	EncodingName       string                 `protobuf:"bytes,3,opt,name=encoding_name,json=encodingName,proto3" json:"encoding_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokensConfiguration) Reset() {
	*x = TokensConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensConfiguration) ProtoMessage() {}

func (x *TokensConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensConfiguration.ProtoReflect.Descriptor instead.
func (*TokensConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *TokensConfiguration) GetMaxChunkSizeTokens() int32 {
	if x != nil {
		return x.MaxChunkSizeTokens
	}
	return 0
}

func (x *TokensConfiguration) GetChunkOverlapTokens() int32 {
	if x != nil {
		return x.ChunkOverlapTokens
	}
	return 0
}

func (x *TokensConfiguration) GetEncodingName() string {
	if x != nil {
		return x.EncodingName
	}
	return ""
}

var File_xai_api_v1_types_proto protoreflect.FileDescriptor

const file_xai_api_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16xai/api/v1/types.proto\x12\x03rag\"z\n" +
	"\fIndexedChunk\x12!\n" +
	"\fchunk_number\x18\x01 \x01(\rR\vchunkNumber\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1b\n" +
	"\tdata_hash\x18\x04 \x01(\fR\bdataHash\"3\n" +
	"\x12IndexConfiguration\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"\x9b\x02\n" +
	"\x12ChunkConfiguration\x12J\n" +
	"\x13chars_configuration\x18\x01 \x01(\v2\x17.rag.CharsConfigurationH\x00R\x12charsConfiguration\x12M\n" +
	"\x14tokens_configuration\x18\x02 \x01(\v2\x18.rag.TokensConfigurationH\x00R\x13tokensConfiguration\x12)\n" +
	"\x10strip_whitespace\x18\x03 \x01(\bR\x0fstripWhitespace\x125\n" +
	"\x17inject_name_into_chunks\x18\x04 \x01(\bR\x14injectNameIntoChunksB\b\n" +
	"\x06config\"u\n" +
	"\x12CharsConfiguration\x12/\n" +
	"\x14max_chunk_size_chars\x18\x01 \x01(\x05R\x11maxChunkSizeChars\x12.\n" +
	"\x13chunk_overlap_chars\x18\x02 \x01(\x05R\x11chunkOverlapChars\"\x9f\x01\n" +
	"\x13TokensConfiguration\x121\n" +
	"\x15max_chunk_size_tokens\x18\x01 \x01(\x05R\x12maxChunkSizeTokens\x120\n" +
	"\x14chunk_overlap_tokens\x18\x02 \x01(\x05R\x12chunkOverlapTokens\x12#\n" +
	"\rencoding_name\x18\x03 \x01(\tR\fencodingNameBA\n" +
	"\acom.ragB\n" +
	"TypesProtoP\x01\xa2\x02\x03RXX\xaa\x02\x03Rag\xca\x02\x03Rag\xe2\x02\x0fRag\\GPBMetadata\xea\x02\x03Ragb\x06proto3"

var (
	file_xai_api_v1_types_proto_rawDescOnce sync.Once
	file_xai_api_v1_types_proto_rawDescData []byte
)

func file_xai_api_v1_types_proto_rawDescGZIP() []byte {
	file_xai_api_v1_types_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xai_api_v1_types_proto_rawDesc), len(file_xai_api_v1_types_proto_rawDesc)))
	})
	return file_xai_api_v1_types_proto_rawDescData
}

var file_xai_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_xai_api_v1_types_proto_goTypes = []any{
	(*IndexedChunk)(nil),        // 0: rag.IndexedChunk
	(*IndexConfiguration)(nil),  // 1: rag.IndexConfiguration
	(*ChunkConfiguration)(nil),  // 2: rag.ChunkConfiguration
	(*CharsConfiguration)(nil),  // 3: rag.CharsConfiguration
	(*TokensConfiguration)(nil), // 4: rag.TokensConfiguration
}
var file_xai_api_v1_types_proto_depIdxs = []int32{
	3, // 0: rag.ChunkConfiguration.chars_configuration:type_name -> rag.CharsConfiguration
	4, // 1: rag.ChunkConfiguration.tokens_configuration:type_name -> rag.TokensConfiguration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xai_api_v1_types_proto_init() }
func file_xai_api_v1_types_proto_init() {
	if File_xai_api_v1_types_proto != nil {
		return
	}
	file_xai_api_v1_types_proto_msgTypes[2].OneofWrappers = []any{
		(*ChunkConfiguration_CharsConfiguration)(nil),
		(*ChunkConfiguration_TokensConfiguration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xai_api_v1_types_proto_rawDesc), len(file_xai_api_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xai_api_v1_types_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_types_proto_depIdxs,
		MessageInfos:      file_xai_api_v1_types_proto_msgTypes,
	}.Build()
	File_xai_api_v1_types_proto = out.File
	file_xai_api_v1_types_proto_goTypes = nil
	file_xai_api_v1_types_proto_depIdxs = nil
}
