version: "2"

run:
  modules-download-mode: mod
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
      path: stdout

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

  settings:
    gofmt:
      simplify: true
    gofumpt:
      module-path: github.com/zchee/tumix
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/zchee/tumix
        - github.com/zchee/tumix/gollm/xai

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    # - cyclop
    # - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint

  settings:
    asasalint:
      use-builtin-exclusions: true
    bidichk:
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 15
      package-average: 0.5
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
      ignore-underscore-vars: false
      disable-dec-num-check: false
      disable-type-dec-num-check: false
      disable-const-dec-num-check: false
      disable-var-dec-num-check: false
      disable-dec-order-check: false
      disable-init-func-first-check: false
    depguard:
      rules:
        stdlib_v2:
          list-mode: original
          files:
            - $all
          deny:
            - pkg: "encoding/json$"
              desc: Use "encoding/json/v2" instead of.
            - pkg: "math/rand$"
              desc: Use "math/rand/v2" instead of.
    dogsled:
      max-blank-identifiers: 3
    dupl:
      threshold: 150
    dupword:
      keywords:
        - the
        - and
        - a
      ignore:
        - 0C0C
    errcheck:
      check-type-assertions: false
      disable-default-exclusions: true
      check-blank: true
      exclude-functions:
        - (*bytes.Buffer).Write
        - (*strings.Builder).WriteString
      verbose: true
    errchkjson:
      check-error-free-encoding: true
      report-no-exported: false
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    funlen:
      lines: 120
      statements: 60
      ignore-comments: true
    gocognit:
      min-complexity: 25
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 3
      numbers: true
      min: 3
      max: 3
      ignore-calls: true
    gocritic:
      enable-all: true
      disabled-checks:
        - commentedOutCode
        - whyNoLint
      settings:
        hugeParam:
          sizeThreshold: 80
        rangeExprCopy:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 128
    gocyclo:
      min-complexity: 20
    godot:
      scope: declarations
      capital: false
      period: true
    goheader:
      template: |-
        Copyright {{ YEAR }} The tumix Authors.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

        	http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

        SPDX-License-Identifier: Apache-2.0
    gosec:
      excludes:
        - G301
    govet:
      disable:
        - fieldalignment
      enable-all: true
    importas:
      no-unaliased: true
      no-extra-aliases: false
    inamedparam:
      skip-single-param: false
    interfacebloat:
      max: 10
    lll:
      line-length: 250
      tab-width: 1
    maintidx:
      under: 15
    makezero:
      always: false
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: line-length-limit
          severity: warning
          disabled: false
          exclude: [""]
          arguments: [120]
      max-open-files: 2048
      confidence: 0.1
      severity: error
      enable-all-rules: true
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: false
      no-global: ""
      context: all
      static-msg: false
      no-raw-keys: false
      key-naming-case: snake
      args-on-sep-lines: false
    spancheck:
      checks:
        - end
        - record-error
        - set-status
      ignore-check-signatures:
        - telemetry.RecordError
    testpackage:
      skip-regexp: .*(export)_test\.go
    unconvert:
      fast-math: true
      safe: true
    unparam:
      check-exported: true
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: true
      generated-is-used: true
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: false
      time-layout: true
      crypto-hash: true
      tls-signature-scheme: false
      constant-kind: false
    varnamelen:
      max-distance: 5
      min-name-length: 1
      check-receiver: true
      check-return: true
      ignore-type-assert-ok: false
      ignore-map-index-ok: false
      ignore-chan-recv-ok: false
    whitespace:
      multi-if: false
      multi-func: true

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - decorder
          - gosec
          - revive
          - wrapcheck
        path: gollm/xai

      - linters:
          - goheader
        path: gollm/xai/internal/grpccodec/mem

      - linters:
          - unparam
        text: "(\\*Reader).Close" # io.Closer
        path: gollm/xai/internal/grpccodec/mem

      - linters:
          - decorder
          - revive
          - wrapcheck
          - cyclop
        path: gollm/xai/examples

      - linters:
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - wrapcheck
        path: _test\.go

      - linters:
          - gocritic
        path: (.*)?_example_test.go

      - linters:
          - govet
        text: 'shadow: declaration of "err|ok|ctx"'

      - linters:
          - nlreturn
        text: continue with no blank line before

      - path: (.+)\.go$
        text: G404

      - path: (.+)\.go$
        text: ST1003

      - path: (.+)\.go$
        text: Error return value of `.*.Add(Array|Object)` is not checked

      - linters:
          - cyclop
          - goconst
        path: (.+)_test\.go

    paths:
      - third_party$
      - builtin$
      - examples$
