// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20251122131602-5bc3a6fc1d03
// source: xai/api/v1/usage.proto

package v1

import (
	fmt "fmt"
	protohelpers "github.com/gaudiy/vtprotobuf/protohelpers"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *SamplingUsage) CloneVT() *SamplingUsage {
	if m == nil {
		return (*SamplingUsage)(nil)
	}
	r := new(SamplingUsage)
	r.CompletionTokens = m.CompletionTokens
	r.ReasoningTokens = m.ReasoningTokens
	r.PromptTokens = m.PromptTokens
	r.TotalTokens = m.TotalTokens
	r.PromptTextTokens = m.PromptTextTokens
	r.CachedPromptTextTokens = m.CachedPromptTextTokens
	r.PromptImageTokens = m.PromptImageTokens
	r.NumSourcesUsed = m.NumSourcesUsed
	if rhs := m.ServerSideToolsUsed; rhs != nil {
		tmpContainer := make([]ServerSideTool, len(rhs))
		copy(tmpContainer, rhs)
		r.ServerSideToolsUsed = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *SamplingUsage) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *EmbeddingUsage) CloneVT() *EmbeddingUsage {
	if m == nil {
		return (*EmbeddingUsage)(nil)
	}
	r := new(EmbeddingUsage)
	r.NumTextEmbeddings = m.NumTextEmbeddings
	r.NumImageEmbeddings = m.NumImageEmbeddings
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *EmbeddingUsage) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *SamplingUsage) EqualVT(that *SamplingUsage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.CompletionTokens != that.CompletionTokens {
		return false
	}
	if this.PromptTokens != that.PromptTokens {
		return false
	}
	if this.TotalTokens != that.TotalTokens {
		return false
	}
	if this.PromptTextTokens != that.PromptTextTokens {
		return false
	}
	if this.PromptImageTokens != that.PromptImageTokens {
		return false
	}
	if this.ReasoningTokens != that.ReasoningTokens {
		return false
	}
	if this.CachedPromptTextTokens != that.CachedPromptTextTokens {
		return false
	}
	if this.NumSourcesUsed != that.NumSourcesUsed {
		return false
	}
	if len(this.ServerSideToolsUsed) != len(that.ServerSideToolsUsed) {
		return false
	}
	for i, vx := range this.ServerSideToolsUsed {
		vy := that.ServerSideToolsUsed[i]
		if vx != vy {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SamplingUsage) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*SamplingUsage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *EmbeddingUsage) EqualVT(that *EmbeddingUsage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.NumTextEmbeddings != that.NumTextEmbeddings {
		return false
	}
	if this.NumImageEmbeddings != that.NumImageEmbeddings {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *EmbeddingUsage) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*EmbeddingUsage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (m *SamplingUsage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SamplingUsage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *SamplingUsage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.ServerSideToolsUsed) > 0 {
		var pksize2 int
		for _, num := range m.ServerSideToolsUsed {
			pksize2 += protohelpers.SizeOfVarint(uint64(num))
		}
		i -= pksize2
		j1 := i
		for _, num1 := range m.ServerSideToolsUsed {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA[j1] = uint8(num)
			j1++
		}
		i = protohelpers.EncodeVarint(dAtA, i, uint64(pksize2))
		i--
		dAtA[i] = 0x4a
	}
	if m.NumSourcesUsed != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.NumSourcesUsed))
		i--
		dAtA[i] = 0x40
	}
	if m.CachedPromptTextTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.CachedPromptTextTokens))
		i--
		dAtA[i] = 0x38
	}
	if m.ReasoningTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.ReasoningTokens))
		i--
		dAtA[i] = 0x30
	}
	if m.PromptImageTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PromptImageTokens))
		i--
		dAtA[i] = 0x28
	}
	if m.PromptTextTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PromptTextTokens))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.TotalTokens))
		i--
		dAtA[i] = 0x18
	}
	if m.PromptTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PromptTokens))
		i--
		dAtA[i] = 0x10
	}
	if m.CompletionTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.CompletionTokens))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EmbeddingUsage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmbeddingUsage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *EmbeddingUsage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.NumImageEmbeddings != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.NumImageEmbeddings))
		i--
		dAtA[i] = 0x10
	}
	if m.NumTextEmbeddings != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.NumTextEmbeddings))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SamplingUsage) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SamplingUsage) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *SamplingUsage) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.ServerSideToolsUsed) > 0 {
		var pksize2 int
		for _, num := range m.ServerSideToolsUsed {
			pksize2 += protohelpers.SizeOfVarint(uint64(num))
		}
		i -= pksize2
		j1 := i
		for _, num1 := range m.ServerSideToolsUsed {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA[j1] = uint8(num)
			j1++
		}
		i = protohelpers.EncodeVarint(dAtA, i, uint64(pksize2))
		i--
		dAtA[i] = 0x4a
	}
	if m.NumSourcesUsed != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.NumSourcesUsed))
		i--
		dAtA[i] = 0x40
	}
	if m.CachedPromptTextTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.CachedPromptTextTokens))
		i--
		dAtA[i] = 0x38
	}
	if m.ReasoningTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.ReasoningTokens))
		i--
		dAtA[i] = 0x30
	}
	if m.PromptImageTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PromptImageTokens))
		i--
		dAtA[i] = 0x28
	}
	if m.PromptTextTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PromptTextTokens))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.TotalTokens))
		i--
		dAtA[i] = 0x18
	}
	if m.PromptTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PromptTokens))
		i--
		dAtA[i] = 0x10
	}
	if m.CompletionTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.CompletionTokens))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EmbeddingUsage) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmbeddingUsage) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *EmbeddingUsage) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.NumImageEmbeddings != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.NumImageEmbeddings))
		i--
		dAtA[i] = 0x10
	}
	if m.NumTextEmbeddings != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.NumTextEmbeddings))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SamplingUsage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CompletionTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.CompletionTokens))
	}
	if m.PromptTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.PromptTokens))
	}
	if m.TotalTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.TotalTokens))
	}
	if m.PromptTextTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.PromptTextTokens))
	}
	if m.PromptImageTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.PromptImageTokens))
	}
	if m.ReasoningTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.ReasoningTokens))
	}
	if m.CachedPromptTextTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.CachedPromptTextTokens))
	}
	if m.NumSourcesUsed != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.NumSourcesUsed))
	}
	if len(m.ServerSideToolsUsed) > 0 {
		l = 0
		for _, e := range m.ServerSideToolsUsed {
			l += protohelpers.SizeOfVarint(uint64(e))
		}
		n += 1 + protohelpers.SizeOfVarint(uint64(l)) + l
	}
	n += len(m.unknownFields)
	return n
}

func (m *EmbeddingUsage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumTextEmbeddings != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.NumTextEmbeddings))
	}
	if m.NumImageEmbeddings != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.NumImageEmbeddings))
	}
	n += len(m.unknownFields)
	return n
}

func (m *SamplingUsage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protohelpers.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SamplingUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SamplingUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTokens", wireType)
			}
			m.CompletionTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletionTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromptTokens", wireType)
			}
			m.PromptTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PromptTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTokens", wireType)
			}
			m.TotalTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromptTextTokens", wireType)
			}
			m.PromptTextTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PromptTextTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromptImageTokens", wireType)
			}
			m.PromptImageTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PromptImageTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasoningTokens", wireType)
			}
			m.ReasoningTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReasoningTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CachedPromptTextTokens", wireType)
			}
			m.CachedPromptTextTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CachedPromptTextTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSourcesUsed", wireType)
			}
			m.NumSourcesUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSourcesUsed |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType == 0 {
				var v ServerSideTool
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protohelpers.ErrIntOverflow
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= ServerSideTool(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ServerSideToolsUsed = append(m.ServerSideToolsUsed, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protohelpers.ErrIntOverflow
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return protohelpers.ErrInvalidLength
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return protohelpers.ErrInvalidLength
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.ServerSideToolsUsed) == 0 {
					m.ServerSideToolsUsed = make([]ServerSideTool, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v ServerSideTool
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protohelpers.ErrIntOverflow
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= ServerSideTool(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ServerSideToolsUsed = append(m.ServerSideToolsUsed, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerSideToolsUsed", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := protohelpers.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protohelpers.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmbeddingUsage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protohelpers.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmbeddingUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmbeddingUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumTextEmbeddings", wireType)
			}
			m.NumTextEmbeddings = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumTextEmbeddings |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumImageEmbeddings", wireType)
			}
			m.NumImageEmbeddings = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumImageEmbeddings |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := protohelpers.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protohelpers.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SamplingUsage) UnmarshalVTUnsafe(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protohelpers.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SamplingUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SamplingUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTokens", wireType)
			}
			m.CompletionTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletionTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromptTokens", wireType)
			}
			m.PromptTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PromptTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTokens", wireType)
			}
			m.TotalTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromptTextTokens", wireType)
			}
			m.PromptTextTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PromptTextTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromptImageTokens", wireType)
			}
			m.PromptImageTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PromptImageTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasoningTokens", wireType)
			}
			m.ReasoningTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReasoningTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CachedPromptTextTokens", wireType)
			}
			m.CachedPromptTextTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CachedPromptTextTokens |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSourcesUsed", wireType)
			}
			m.NumSourcesUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSourcesUsed |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType == 0 {
				var v ServerSideTool
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protohelpers.ErrIntOverflow
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= ServerSideTool(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ServerSideToolsUsed = append(m.ServerSideToolsUsed, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protohelpers.ErrIntOverflow
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return protohelpers.ErrInvalidLength
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return protohelpers.ErrInvalidLength
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.ServerSideToolsUsed) == 0 {
					m.ServerSideToolsUsed = make([]ServerSideTool, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v ServerSideTool
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protohelpers.ErrIntOverflow
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= ServerSideTool(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ServerSideToolsUsed = append(m.ServerSideToolsUsed, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerSideToolsUsed", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := protohelpers.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protohelpers.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmbeddingUsage) UnmarshalVTUnsafe(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protohelpers.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmbeddingUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmbeddingUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumTextEmbeddings", wireType)
			}
			m.NumTextEmbeddings = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumTextEmbeddings |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumImageEmbeddings", wireType)
			}
			m.NumImageEmbeddings = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumImageEmbeddings |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := protohelpers.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protohelpers.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
