// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: xai/management_api/v1/billing.proto

package v1

import (
	analytics "github.com/zchee/tumix/model/xai/shared/analytics"
	billing "github.com/zchee/tumix/model/xai/shared/billing"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Charging status of the invoice.
type InvoiceBundle_Status int32

const (
	InvoiceBundle_INVALID               InvoiceBundle_Status = 0
	InvoiceBundle_PENDING               InvoiceBundle_Status = 1
	InvoiceBundle_PAID                  InvoiceBundle_Status = 2
	InvoiceBundle_WILL_NEVER_BE_CHARGED InvoiceBundle_Status = 3
	InvoiceBundle_FAILED                InvoiceBundle_Status = 4
)

// Enum value maps for InvoiceBundle_Status.
var (
	InvoiceBundle_Status_name = map[int32]string{
		0: "INVALID",
		1: "PENDING",
		2: "PAID",
		3: "WILL_NEVER_BE_CHARGED",
		4: "FAILED",
	}
	InvoiceBundle_Status_value = map[string]int32{
		"INVALID":               0,
		"PENDING":               1,
		"PAID":                  2,
		"WILL_NEVER_BE_CHARGED": 3,
		"FAILED":                4,
	}
)

func (x InvoiceBundle_Status) Enum() *InvoiceBundle_Status {
	p := new(InvoiceBundle_Status)
	*p = x
	return p
}

func (x InvoiceBundle_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceBundle_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_management_api_v1_billing_proto_enumTypes[0].Descriptor()
}

func (InvoiceBundle_Status) Type() protoreflect.EnumType {
	return &file_xai_management_api_v1_billing_proto_enumTypes[0]
}

func (x InvoiceBundle_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceBundle_Status.Descriptor instead.
func (InvoiceBundle_Status) EnumDescriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{19, 0}
}

// The reason for the change.
type PrepaidBalanceChange_ChangeOrigin int32

const (
	PrepaidBalanceChange_INVALID_ORIGIN PrepaidBalanceChange_ChangeOrigin = 0
	PrepaidBalanceChange_PURCHASE       PrepaidBalanceChange_ChangeOrigin = 10 // Purchase by user. `amount` field will be negative.
	PrepaidBalanceChange_SPEND          PrepaidBalanceChange_ChangeOrigin = 20 // Spending by user. `amount` field will be positive.
	PrepaidBalanceChange_REFUND         PrepaidBalanceChange_ChangeOrigin = 30 // A refund issued to user. `amount` field will be negative.
	PrepaidBalanceChange_MANUAL         PrepaidBalanceChange_ChangeOrigin = 40 // Can be either positive or negative, performed by xAI staff.
)

// Enum value maps for PrepaidBalanceChange_ChangeOrigin.
var (
	PrepaidBalanceChange_ChangeOrigin_name = map[int32]string{
		0:  "INVALID_ORIGIN",
		10: "PURCHASE",
		20: "SPEND",
		30: "REFUND",
		40: "MANUAL",
	}
	PrepaidBalanceChange_ChangeOrigin_value = map[string]int32{
		"INVALID_ORIGIN": 0,
		"PURCHASE":       10,
		"SPEND":          20,
		"REFUND":         30,
		"MANUAL":         40,
	}
)

func (x PrepaidBalanceChange_ChangeOrigin) Enum() *PrepaidBalanceChange_ChangeOrigin {
	p := new(PrepaidBalanceChange_ChangeOrigin)
	*p = x
	return p
}

func (x PrepaidBalanceChange_ChangeOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrepaidBalanceChange_ChangeOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_management_api_v1_billing_proto_enumTypes[1].Descriptor()
}

func (PrepaidBalanceChange_ChangeOrigin) Type() protoreflect.EnumType {
	return &file_xai_management_api_v1_billing_proto_enumTypes[1]
}

func (x PrepaidBalanceChange_ChangeOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrepaidBalanceChange_ChangeOrigin.Descriptor instead.
func (PrepaidBalanceChange_ChangeOrigin) EnumDescriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{23, 0}
}

// Status of the top up.
type PrepaidBalanceChange_TopUpStatus int32

const (
	PrepaidBalanceChange_INVALID_STATUS             PrepaidBalanceChange_TopUpStatus = 0
	PrepaidBalanceChange_TO_GENERATE_INVOICE        PrepaidBalanceChange_TopUpStatus = 10
	PrepaidBalanceChange_FAILED_TO_GENERATE_INVOICE PrepaidBalanceChange_TopUpStatus = 20
	PrepaidBalanceChange_TO_CHARGE                  PrepaidBalanceChange_TopUpStatus = 30
	PrepaidBalanceChange_FAILED_TO_CHARGE           PrepaidBalanceChange_TopUpStatus = 40
	PrepaidBalanceChange_SUCCEEDED                  PrepaidBalanceChange_TopUpStatus = 50
)

// Enum value maps for PrepaidBalanceChange_TopUpStatus.
var (
	PrepaidBalanceChange_TopUpStatus_name = map[int32]string{
		0:  "INVALID_STATUS",
		10: "TO_GENERATE_INVOICE",
		20: "FAILED_TO_GENERATE_INVOICE",
		30: "TO_CHARGE",
		40: "FAILED_TO_CHARGE",
		50: "SUCCEEDED",
	}
	PrepaidBalanceChange_TopUpStatus_value = map[string]int32{
		"INVALID_STATUS":             0,
		"TO_GENERATE_INVOICE":        10,
		"FAILED_TO_GENERATE_INVOICE": 20,
		"TO_CHARGE":                  30,
		"FAILED_TO_CHARGE":           40,
		"SUCCEEDED":                  50,
	}
)

func (x PrepaidBalanceChange_TopUpStatus) Enum() *PrepaidBalanceChange_TopUpStatus {
	p := new(PrepaidBalanceChange_TopUpStatus)
	*p = x
	return p
}

func (x PrepaidBalanceChange_TopUpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrepaidBalanceChange_TopUpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_management_api_v1_billing_proto_enumTypes[2].Descriptor()
}

func (PrepaidBalanceChange_TopUpStatus) Type() protoreflect.EnumType {
	return &file_xai_management_api_v1_billing_proto_enumTypes[2]
}

func (x PrepaidBalanceChange_TopUpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrepaidBalanceChange_TopUpStatus.Descriptor instead.
func (PrepaidBalanceChange_TopUpStatus) EnumDescriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{23, 1}
}

// Request to set the billing information on the team.
type SetBillingInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team.
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Billing information for the team to set.
	BillingInfo   *billing.BillingInfo `protobuf:"bytes,10,opt,name=billing_info,json=billingInfo,proto3" json:"billing_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBillingInfoReq) Reset() {
	*x = SetBillingInfoReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBillingInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBillingInfoReq) ProtoMessage() {}

func (x *SetBillingInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBillingInfoReq.ProtoReflect.Descriptor instead.
func (*SetBillingInfoReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *SetBillingInfoReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SetBillingInfoReq) GetBillingInfo() *billing.BillingInfo {
	if x != nil {
		return x.BillingInfo
	}
	return nil
}

// Response of setting the billing information on the team.
type SetBillingInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBillingInfoResp) Reset() {
	*x = SetBillingInfoResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBillingInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBillingInfoResp) ProtoMessage() {}

func (x *SetBillingInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBillingInfoResp.ProtoReflect.Descriptor instead.
func (*SetBillingInfoResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{1}
}

// Request for getting billing information.
type GetBillingInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team.
	TeamId        string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingInfoReq) Reset() {
	*x = GetBillingInfoReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingInfoReq) ProtoMessage() {}

func (x *GetBillingInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingInfoReq.ProtoReflect.Descriptor instead.
func (*GetBillingInfoReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillingInfoReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Response containing the billing information of the team.
type GetBillingInfoResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Billing information of the team.
	BillingInfo   *billing.BillingInfo `protobuf:"bytes,10,opt,name=billing_info,json=billingInfo,proto3" json:"billing_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingInfoResp) Reset() {
	*x = GetBillingInfoResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingInfoResp) ProtoMessage() {}

func (x *GetBillingInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingInfoResp.ProtoReflect.Descriptor instead.
func (*GetBillingInfoResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillingInfoResp) GetBillingInfo() *billing.BillingInfo {
	if x != nil {
		return x.BillingInfo
	}
	return nil
}

// List payment methods that belong to the team.
type ListPaymentMethodsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team.
	TeamId        string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentMethodsReq) Reset() {
	*x = ListPaymentMethodsReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsReq) ProtoMessage() {}

func (x *ListPaymentMethodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsReq.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *ListPaymentMethodsReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Represents an incomplete attempt to add a payment method.
// Might resolve into a payment method.
type PendingPaymentMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verification URL for ACH micro deposits that verifies the account.
	AchMicrodepositHostedVerificationUrl string `protobuf:"bytes,10,opt,name=ach_microdeposit_hosted_verification_url,json=achMicrodepositHostedVerificationUrl,proto3" json:"ach_microdeposit_hosted_verification_url,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PendingPaymentMethod) Reset() {
	*x = PendingPaymentMethod{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingPaymentMethod) ProtoMessage() {}

func (x *PendingPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingPaymentMethod.ProtoReflect.Descriptor instead.
func (*PendingPaymentMethod) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *PendingPaymentMethod) GetAchMicrodepositHostedVerificationUrl() string {
	if x != nil {
		return x.AchMicrodepositHostedVerificationUrl
	}
	return ""
}

// Response containing a list of payment methods for the team.
type ListPaymentMethodsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payment methods on file.
	PaymentMethods []*billing.PaymentMethod `protobuf:"bytes,10,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	// Pending payment method.
	PendingPaymentMethod *PendingPaymentMethod `protobuf:"bytes,21,opt,name=pending_payment_method,json=pendingPaymentMethod,proto3" json:"pending_payment_method,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListPaymentMethodsResp) Reset() {
	*x = ListPaymentMethodsResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsResp) ProtoMessage() {}

func (x *ListPaymentMethodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsResp.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentMethodsResp) GetPaymentMethods() []*billing.PaymentMethod {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

func (x *ListPaymentMethodsResp) GetPendingPaymentMethod() *PendingPaymentMethod {
	if x != nil {
		return x.PendingPaymentMethod
	}
	return nil
}

// Request to set default payment method on a team.
type SetDefaultPaymentMethodReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team.
	TeamId string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// ID of the payment method that you want to set as default.
	PaymentMethodId string `protobuf:"bytes,20,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDefaultPaymentMethodReq) Reset() {
	*x = SetDefaultPaymentMethodReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultPaymentMethodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultPaymentMethodReq) ProtoMessage() {}

func (x *SetDefaultPaymentMethodReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultPaymentMethodReq.ProtoReflect.Descriptor instead.
func (*SetDefaultPaymentMethodReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *SetDefaultPaymentMethodReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SetDefaultPaymentMethodReq) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

// Response to setting default payment method.
type SetDefaultPaymentMethodResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultPaymentMethodResp) Reset() {
	*x = SetDefaultPaymentMethodResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultPaymentMethodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultPaymentMethodResp) ProtoMessage() {}

func (x *SetDefaultPaymentMethodResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultPaymentMethodResp.ProtoReflect.Descriptor instead.
func (*SetDefaultPaymentMethodResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{8}
}

// Each line on the invoice.
type Line struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster on which the resource is consumed.
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// The description of the line item.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The unit in which the price is measured.
	UnitType string `protobuf:"bytes,3,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	// The price per unit (1/1_000_000 USD cents).
	UnitPrice int64 `protobuf:"varint,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	// The number of units.
	NumUnits int64 `protobuf:"varint,5,opt,name=num_units,json=numUnits,proto3" json:"num_units,omitempty"`
	// Total amount of the line item (USD cents).
	Amount        int64 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *Line) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Line) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Line) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *Line) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *Line) GetNumUnits() int64 {
	if x != nil {
		return x.NumUnits
	}
	return 0
}

func (x *Line) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// The invoice object.
type CoreInvoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Line items on the invoice.
	Lines []*Line `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	// Amount before VAT (USD cents).
	AmountBeforeVat int64 `protobuf:"varint,2,opt,name=amount_before_vat,json=amountBeforeVat,proto3" json:"amount_before_vat,omitempty"`
	// VAT (USD cents).
	VatCost int64 `protobuf:"varint,3,opt,name=vat_cost,json=vatCost,proto3" json:"vat_cost,omitempty"`
	// Total amount after VAT (USD cents).
	AmountAfterVat int64 `protobuf:"varint,4,opt,name=amount_after_vat,json=amountAfterVat,proto3" json:"amount_after_vat,omitempty"`
	// Automatically issued credits (USD cents).
	AutoCreditsIssued int64 `protobuf:"varint,5,opt,name=auto_credits_issued,json=autoCreditsIssued,proto3" json:"auto_credits_issued,omitempty"`
	// Default credit issued (USD cents).
	DefaultCreditsIssued int64 `protobuf:"varint,6,opt,name=default_credits_issued,json=defaultCreditsIssued,proto3" json:"default_credits_issued,omitempty"`
	// Total amount (USD cents).
	TotalWithCorr *billing.Cent `protobuf:"bytes,9,opt,name=total_with_corr,json=totalWithCorr,proto3" json:"total_with_corr,omitempty"`
	// Total prepaid credits in the team before the invoice.
	PrepaidCredits *billing.Cent `protobuf:"bytes,8,opt,name=prepaid_credits,json=prepaidCredits,proto3" json:"prepaid_credits,omitempty"`
	// Prepaid credits used to pay for the invoice.
	PrepaidCreditsUsed *billing.Cent `protobuf:"bytes,7,opt,name=prepaid_credits_used,json=prepaidCreditsUsed,proto3" json:"prepaid_credits_used,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CoreInvoice) Reset() {
	*x = CoreInvoice{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInvoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInvoice) ProtoMessage() {}

func (x *CoreInvoice) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInvoice.ProtoReflect.Descriptor instead.
func (*CoreInvoice) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{10}
}

func (x *CoreInvoice) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *CoreInvoice) GetAmountBeforeVat() int64 {
	if x != nil {
		return x.AmountBeforeVat
	}
	return 0
}

func (x *CoreInvoice) GetVatCost() int64 {
	if x != nil {
		return x.VatCost
	}
	return 0
}

func (x *CoreInvoice) GetAmountAfterVat() int64 {
	if x != nil {
		return x.AmountAfterVat
	}
	return 0
}

func (x *CoreInvoice) GetAutoCreditsIssued() int64 {
	if x != nil {
		return x.AutoCreditsIssued
	}
	return 0
}

func (x *CoreInvoice) GetDefaultCreditsIssued() int64 {
	if x != nil {
		return x.DefaultCreditsIssued
	}
	return 0
}

func (x *CoreInvoice) GetTotalWithCorr() *billing.Cent {
	if x != nil {
		return x.TotalWithCorr
	}
	return nil
}

func (x *CoreInvoice) GetPrepaidCredits() *billing.Cent {
	if x != nil {
		return x.PrepaidCredits
	}
	return nil
}

func (x *CoreInvoice) GetPrepaidCreditsUsed() *billing.Cent {
	if x != nil {
		return x.PrepaidCreditsUsed
	}
	return nil
}

// Request to get the payment amount of current month's monthly invoice.
type GetAmountToPayReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team.
	TeamId        string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAmountToPayReq) Reset() {
	*x = GetAmountToPayReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAmountToPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmountToPayReq) ProtoMessage() {}

func (x *GetAmountToPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmountToPayReq.ProtoReflect.Descriptor instead.
func (*GetAmountToPayReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{11}
}

func (x *GetAmountToPayReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Response of the payment amount of current month's monthly invoice.
type GetAmountToPayResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current partial invoice.
	CoreInvoice *CoreInvoice `protobuf:"bytes,1,opt,name=core_invoice,json=coreInvoice,proto3" json:"core_invoice,omitempty"`
	// The effective current spending limit in USD cents.
	EffectiveSpendingLimit int64 `protobuf:"varint,2,opt,name=effective_spending_limit,json=effectiveSpendingLimit,proto3" json:"effective_spending_limit,omitempty"`
	// The current default credits in USD cents.
	DefaultCredits int64 `protobuf:"varint,3,opt,name=default_credits,json=defaultCredits,proto3" json:"default_credits,omitempty"`
	// The current billing cycle whose invoice data is reported here.
	BillingCycle  *BillingCycle `protobuf:"bytes,4,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAmountToPayResp) Reset() {
	*x = GetAmountToPayResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAmountToPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmountToPayResp) ProtoMessage() {}

func (x *GetAmountToPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmountToPayResp.ProtoReflect.Descriptor instead.
func (*GetAmountToPayResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{12}
}

func (x *GetAmountToPayResp) GetCoreInvoice() *CoreInvoice {
	if x != nil {
		return x.CoreInvoice
	}
	return nil
}

func (x *GetAmountToPayResp) GetEffectiveSpendingLimit() int64 {
	if x != nil {
		return x.EffectiveSpendingLimit
	}
	return 0
}

func (x *GetAmountToPayResp) GetDefaultCredits() int64 {
	if x != nil {
		return x.DefaultCredits
	}
	return 0
}

func (x *GetAmountToPayResp) GetBillingCycle() *BillingCycle {
	if x != nil {
		return x.BillingCycle
	}
	return nil
}

// Request to get historical API usage.
type AnalyzeBillingItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual analysis request.
	AnalyticsRequest *analytics.AnalyticsRequest `protobuf:"bytes,1,opt,name=analytics_request,json=analyticsRequest,proto3" json:"analytics_request,omitempty"`
	// The team whose billing records to analyze.
	TeamId        string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBillingItemsRequest) Reset() {
	*x = AnalyzeBillingItemsRequest{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBillingItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBillingItemsRequest) ProtoMessage() {}

func (x *AnalyzeBillingItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBillingItemsRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBillingItemsRequest) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzeBillingItemsRequest) GetAnalyticsRequest() *analytics.AnalyticsRequest {
	if x != nil {
		return x.AnalyticsRequest
	}
	return nil
}

func (x *AnalyzeBillingItemsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type BillingCycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingCycle) Reset() {
	*x = BillingCycle{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingCycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingCycle) ProtoMessage() {}

func (x *BillingCycle) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingCycle.ProtoReflect.Descriptor instead.
func (*BillingCycle) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{14}
}

func (x *BillingCycle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BillingCycle) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type ChargerAttempt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ticket          int32                  `protobuf:"varint,10,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Successful      bool                   `protobuf:"varint,20,opt,name=successful,proto3" json:"successful,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,30,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"` // The payment method that was tried in this attempt.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChargerAttempt) Reset() {
	*x = ChargerAttempt{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargerAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargerAttempt) ProtoMessage() {}

func (x *ChargerAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargerAttempt.ProtoReflect.Descriptor instead.
func (*ChargerAttempt) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{15}
}

func (x *ChargerAttempt) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *ChargerAttempt) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ChargerAttempt) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

type MonthlyInvoiceBundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The billing cycle the invoice applies to.
	BillingCycle *BillingCycle `protobuf:"bytes,10,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	// Default credits applied to the invoice.
	DefaultCreditsIssued *billing.Cent `protobuf:"bytes,20,opt,name=default_credits_issued,json=defaultCreditsIssued,proto3" json:"default_credits_issued,omitempty"`
	// Automatically issued credits.
	AutoCreditsIssued *billing.Cent `protobuf:"bytes,30,opt,name=auto_credits_issued,json=autoCreditsIssued,proto3" json:"auto_credits_issued,omitempty"`
	// Prepaid token on file to be spent.
	PrepaidTokensToSpend *billing.Cent `protobuf:"bytes,35,opt,name=prepaid_tokens_to_spend,json=prepaidTokensToSpend,proto3" json:"prepaid_tokens_to_spend,omitempty"`
	// The billing items csv file suffix, used by xAI processes.
	BillingItemsCsvAssetKeySuffix *string `protobuf:"bytes,40,opt,name=billing_items_csv_asset_key_suffix,json=billingItemsCsvAssetKeySuffix,proto3,oneof" json:"billing_items_csv_asset_key_suffix,omitempty"`
	// The billing items corrections csv file suffix, used by xAI processes.
	CorrectionsCsvAssetKeySuffix *string `protobuf:"bytes,50,opt,name=corrections_csv_asset_key_suffix,json=correctionsCsvAssetKeySuffix,proto3,oneof" json:"corrections_csv_asset_key_suffix,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *MonthlyInvoiceBundle) Reset() {
	*x = MonthlyInvoiceBundle{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyInvoiceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyInvoiceBundle) ProtoMessage() {}

func (x *MonthlyInvoiceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyInvoiceBundle.ProtoReflect.Descriptor instead.
func (*MonthlyInvoiceBundle) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{16}
}

func (x *MonthlyInvoiceBundle) GetBillingCycle() *BillingCycle {
	if x != nil {
		return x.BillingCycle
	}
	return nil
}

func (x *MonthlyInvoiceBundle) GetDefaultCreditsIssued() *billing.Cent {
	if x != nil {
		return x.DefaultCreditsIssued
	}
	return nil
}

func (x *MonthlyInvoiceBundle) GetAutoCreditsIssued() *billing.Cent {
	if x != nil {
		return x.AutoCreditsIssued
	}
	return nil
}

func (x *MonthlyInvoiceBundle) GetPrepaidTokensToSpend() *billing.Cent {
	if x != nil {
		return x.PrepaidTokensToSpend
	}
	return nil
}

func (x *MonthlyInvoiceBundle) GetBillingItemsCsvAssetKeySuffix() string {
	if x != nil && x.BillingItemsCsvAssetKeySuffix != nil {
		return *x.BillingItemsCsvAssetKeySuffix
	}
	return ""
}

func (x *MonthlyInvoiceBundle) GetCorrectionsCsvAssetKeySuffix() string {
	if x != nil && x.CorrectionsCsvAssetKeySuffix != nil {
		return *x.CorrectionsCsvAssetKeySuffix
	}
	return ""
}

type PrepaidInvoiceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepaidInvoiceBundle) Reset() {
	*x = PrepaidInvoiceBundle{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepaidInvoiceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepaidInvoiceBundle) ProtoMessage() {}

func (x *PrepaidInvoiceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepaidInvoiceBundle.ProtoReflect.Descriptor instead.
func (*PrepaidInvoiceBundle) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{17}
}

type SubscriptionsInvoiceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsInvoiceBundle) Reset() {
	*x = SubscriptionsInvoiceBundle{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsInvoiceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsInvoiceBundle) ProtoMessage() {}

func (x *SubscriptionsInvoiceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsInvoiceBundle.ProtoReflect.Descriptor instead.
func (*SubscriptionsInvoiceBundle) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{18}
}

// Invoice item.
type InvoiceBundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Team ID.
	TeamId string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The Invoice ID.
	InvoiceId string `protobuf:"bytes,20,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	// The Invoice number.
	InvoiceNumber string `protobuf:"bytes,21,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	// The creation time of the invoice.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The status of the invoice.
	InvoiceStatus InvoiceBundle_Status `protobuf:"varint,40,opt,name=invoice_status,json=invoiceStatus,proto3,enum=prod_mc_billing.InvoiceBundle_Status" json:"invoice_status,omitempty"`
	// When customer is expected to be charged.
	FirstDesiredNextCycleTs *timestamppb.Timestamp `protobuf:"bytes,50,opt,name=first_desired_next_cycle_ts,json=firstDesiredNextCycleTs,proto3" json:"first_desired_next_cycle_ts,omitempty"`
	ChargerAttempts         []*ChargerAttempt      `protobuf:"bytes,60,rep,name=charger_attempts,json=chargerAttempts,proto3" json:"charger_attempts,omitempty"`
	// List of items composing the invoice.
	Lines []*Line `protobuf:"bytes,70,rep,name=lines,proto3" json:"lines,omitempty"`
	// Sub-total of the invoice containing all the cost
	Subtotal int64 `protobuf:"varint,80,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	// without taxes in USD cents.
	Tax int64 `protobuf:"varint,90,opt,name=tax,proto3" json:"tax,omitempty"`
	// Total due for the invoice taxes included in USD cents.
	Total int64 `protobuf:"varint,100,opt,name=total,proto3" json:"total,omitempty"`
	// The invoice pdf suffix.
	InvoicePdfAssetKeySuffix string `protobuf:"bytes,110,opt,name=invoice_pdf_asset_key_suffix,json=invoicePdfAssetKeySuffix,proto3" json:"invoice_pdf_asset_key_suffix,omitempty"`
	// Type of the invoice.
	//
	// Types that are valid to be assigned to Flavour:
	//
	//	*InvoiceBundle_Monthly
	//	*InvoiceBundle_Prepaid
	//	*InvoiceBundle_Subscriptions
	Flavour       isInvoiceBundle_Flavour `protobuf_oneof:"flavour"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceBundle) Reset() {
	*x = InvoiceBundle{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceBundle) ProtoMessage() {}

func (x *InvoiceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceBundle.ProtoReflect.Descriptor instead.
func (*InvoiceBundle) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{19}
}

func (x *InvoiceBundle) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *InvoiceBundle) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *InvoiceBundle) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *InvoiceBundle) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *InvoiceBundle) GetInvoiceStatus() InvoiceBundle_Status {
	if x != nil {
		return x.InvoiceStatus
	}
	return InvoiceBundle_INVALID
}

func (x *InvoiceBundle) GetFirstDesiredNextCycleTs() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstDesiredNextCycleTs
	}
	return nil
}

func (x *InvoiceBundle) GetChargerAttempts() []*ChargerAttempt {
	if x != nil {
		return x.ChargerAttempts
	}
	return nil
}

func (x *InvoiceBundle) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *InvoiceBundle) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *InvoiceBundle) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *InvoiceBundle) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InvoiceBundle) GetInvoicePdfAssetKeySuffix() string {
	if x != nil {
		return x.InvoicePdfAssetKeySuffix
	}
	return ""
}

func (x *InvoiceBundle) GetFlavour() isInvoiceBundle_Flavour {
	if x != nil {
		return x.Flavour
	}
	return nil
}

func (x *InvoiceBundle) GetMonthly() *MonthlyInvoiceBundle {
	if x != nil {
		if x, ok := x.Flavour.(*InvoiceBundle_Monthly); ok {
			return x.Monthly
		}
	}
	return nil
}

func (x *InvoiceBundle) GetPrepaid() *PrepaidInvoiceBundle {
	if x != nil {
		if x, ok := x.Flavour.(*InvoiceBundle_Prepaid); ok {
			return x.Prepaid
		}
	}
	return nil
}

func (x *InvoiceBundle) GetSubscriptions() *SubscriptionsInvoiceBundle {
	if x != nil {
		if x, ok := x.Flavour.(*InvoiceBundle_Subscriptions); ok {
			return x.Subscriptions
		}
	}
	return nil
}

type isInvoiceBundle_Flavour interface {
	isInvoiceBundle_Flavour()
}

type InvoiceBundle_Monthly struct {
	Monthly *MonthlyInvoiceBundle `protobuf:"bytes,120,opt,name=monthly,proto3,oneof"`
}

type InvoiceBundle_Prepaid struct {
	Prepaid *PrepaidInvoiceBundle `protobuf:"bytes,130,opt,name=prepaid,proto3,oneof"`
}

type InvoiceBundle_Subscriptions struct {
	Subscriptions *SubscriptionsInvoiceBundle `protobuf:"bytes,140,opt,name=subscriptions,proto3,oneof"`
}

func (*InvoiceBundle_Monthly) isInvoiceBundle_Flavour() {}

func (*InvoiceBundle_Prepaid) isInvoiceBundle_Flavour() {}

func (*InvoiceBundle_Subscriptions) isInvoiceBundle_Flavour() {}

type InvoiceIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceIds    []string               `protobuf:"bytes,10,rep,name=invoice_ids,json=invoiceIds,proto3" json:"invoice_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceIds) Reset() {
	*x = InvoiceIds{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceIds) ProtoMessage() {}

func (x *InvoiceIds) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceIds.ProtoReflect.Descriptor instead.
func (*InvoiceIds) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{20}
}

func (x *InvoiceIds) GetInvoiceIds() []string {
	if x != nil {
		return x.InvoiceIds
	}
	return nil
}

// Request to list invoices.
type ListInvoicesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team.
	TeamId string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Types that are valid to be assigned to Filter:
	//
	//	*ListInvoicesReq_BillingCycle
	//	*ListInvoicesReq_Since
	//	*ListInvoicesReq_InvoiceIds
	Filter        isListInvoicesReq_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesReq) Reset() {
	*x = ListInvoicesReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesReq) ProtoMessage() {}

func (x *ListInvoicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesReq.ProtoReflect.Descriptor instead.
func (*ListInvoicesReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{21}
}

func (x *ListInvoicesReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListInvoicesReq) GetFilter() isListInvoicesReq_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListInvoicesReq) GetBillingCycle() *BillingCycle {
	if x != nil {
		if x, ok := x.Filter.(*ListInvoicesReq_BillingCycle); ok {
			return x.BillingCycle
		}
	}
	return nil
}

func (x *ListInvoicesReq) GetSince() *BillingCycle {
	if x != nil {
		if x, ok := x.Filter.(*ListInvoicesReq_Since); ok {
			return x.Since
		}
	}
	return nil
}

func (x *ListInvoicesReq) GetInvoiceIds() *InvoiceIds {
	if x != nil {
		if x, ok := x.Filter.(*ListInvoicesReq_InvoiceIds); ok {
			return x.InvoiceIds
		}
	}
	return nil
}

type isListInvoicesReq_Filter interface {
	isListInvoicesReq_Filter()
}

type ListInvoicesReq_BillingCycle struct {
	// Specific billing cycle to retrieve.
	BillingCycle *BillingCycle `protobuf:"bytes,20,opt,name=billing_cycle,json=billingCycle,proto3,oneof"`
}

type ListInvoicesReq_Since struct {
	// Specify since which billing cycle to retrieve.
	Since *BillingCycle `protobuf:"bytes,30,opt,name=since,proto3,oneof"`
}

type ListInvoicesReq_InvoiceIds struct {
	// List invoices by ids
	InvoiceIds *InvoiceIds `protobuf:"bytes,40,opt,name=invoice_ids,json=invoiceIds,proto3,oneof"`
}

func (*ListInvoicesReq_BillingCycle) isListInvoicesReq_Filter() {}

func (*ListInvoicesReq_Since) isListInvoicesReq_Filter() {}

func (*ListInvoicesReq_InvoiceIds) isListInvoicesReq_Filter() {}

// Response containing invoices.
type ListInvoicesResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Invoices.
	Invoices      []*InvoiceBundle `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResp) Reset() {
	*x = ListInvoicesResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResp) ProtoMessage() {}

func (x *ListInvoicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResp.ProtoReflect.Descriptor instead.
func (*ListInvoicesResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{22}
}

func (x *ListInvoicesResp) GetInvoices() []*InvoiceBundle {
	if x != nil {
		return x.Invoices
	}
	return nil
}

// Change item on the prepaid credit balance.
type PrepaidBalanceChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team ID.
	TeamId string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The reason for the change
	ChangeOrigin PrepaidBalanceChange_ChangeOrigin `protobuf:"varint,20,opt,name=change_origin,json=changeOrigin,proto3,enum=prod_mc_billing.PrepaidBalanceChange_ChangeOrigin" json:"change_origin,omitempty"`
	// Status of the top up.
	TopupStatus *PrepaidBalanceChange_TopUpStatus `protobuf:"varint,30,opt,name=topup_status,json=topupStatus,proto3,enum=prod_mc_billing.PrepaidBalanceChange_TopUpStatus,oneof" json:"topup_status,omitempty"`
	// Amount in USD cents.
	Amount *billing.Cent `protobuf:"bytes,40,opt,name=amount,proto3" json:"amount,omitempty"`
	// Invoice ID.
	InvoiceId *string `protobuf:"bytes,50,opt,name=invoice_id,json=invoiceId,proto3,oneof" json:"invoice_id,omitempty"`
	// Invoice number.
	InvoiceNumber *string `protobuf:"bytes,51,opt,name=invoice_number,json=invoiceNumber,proto3,oneof" json:"invoice_number,omitempty"`
	// Creation time of the invoice.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,60,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Calendar year the purchase is made in.
	SpendBpKeyYear *int32 `protobuf:"varint,70,opt,name=spend_bp_key_year,json=spendBpKeyYear,proto3,oneof" json:"spend_bp_key_year,omitempty"`
	// Calendar month the purchase is made in.
	SpendBpKeyMonth *int32 `protobuf:"varint,80,opt,name=spend_bp_key_month,json=spendBpKeyMonth,proto3,oneof" json:"spend_bp_key_month,omitempty"`
	// Creation timestamp.
	CreateTs      *timestamppb.Timestamp `protobuf:"bytes,85,opt,name=create_ts,json=createTs,proto3,oneof" json:"create_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepaidBalanceChange) Reset() {
	*x = PrepaidBalanceChange{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepaidBalanceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepaidBalanceChange) ProtoMessage() {}

func (x *PrepaidBalanceChange) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepaidBalanceChange.ProtoReflect.Descriptor instead.
func (*PrepaidBalanceChange) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{23}
}

func (x *PrepaidBalanceChange) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *PrepaidBalanceChange) GetChangeOrigin() PrepaidBalanceChange_ChangeOrigin {
	if x != nil {
		return x.ChangeOrigin
	}
	return PrepaidBalanceChange_INVALID_ORIGIN
}

func (x *PrepaidBalanceChange) GetTopupStatus() PrepaidBalanceChange_TopUpStatus {
	if x != nil && x.TopupStatus != nil {
		return *x.TopupStatus
	}
	return PrepaidBalanceChange_INVALID_STATUS
}

func (x *PrepaidBalanceChange) GetAmount() *billing.Cent {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PrepaidBalanceChange) GetInvoiceId() string {
	if x != nil && x.InvoiceId != nil {
		return *x.InvoiceId
	}
	return ""
}

func (x *PrepaidBalanceChange) GetInvoiceNumber() string {
	if x != nil && x.InvoiceNumber != nil {
		return *x.InvoiceNumber
	}
	return ""
}

func (x *PrepaidBalanceChange) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *PrepaidBalanceChange) GetSpendBpKeyYear() int32 {
	if x != nil && x.SpendBpKeyYear != nil {
		return *x.SpendBpKeyYear
	}
	return 0
}

func (x *PrepaidBalanceChange) GetSpendBpKeyMonth() int32 {
	if x != nil && x.SpendBpKeyMonth != nil {
		return *x.SpendBpKeyMonth
	}
	return 0
}

func (x *PrepaidBalanceChange) GetCreateTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTs
	}
	return nil
}

// Request to list prepaid credit balance.
type ListPrepaidBalanceChangesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team ID of the team.
	TeamId        string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrepaidBalanceChangesReq) Reset() {
	*x = ListPrepaidBalanceChangesReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrepaidBalanceChangesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrepaidBalanceChangesReq) ProtoMessage() {}

func (x *ListPrepaidBalanceChangesReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrepaidBalanceChangesReq.ProtoReflect.Descriptor instead.
func (*ListPrepaidBalanceChangesReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{24}
}

func (x *ListPrepaidBalanceChangesReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Response for prepaid credit balance.
type ListPrepaidBalanceChangesResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changes of the prepaid credit balance.
	Changes []*PrepaidBalanceChange `protobuf:"bytes,10,rep,name=changes,proto3" json:"changes,omitempty"`
	// The team's currently available prepaid credits (excluding pending
	// charges).
	Total         *billing.Cent `protobuf:"bytes,20,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrepaidBalanceChangesResp) Reset() {
	*x = ListPrepaidBalanceChangesResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrepaidBalanceChangesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrepaidBalanceChangesResp) ProtoMessage() {}

func (x *ListPrepaidBalanceChangesResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrepaidBalanceChangesResp.ProtoReflect.Descriptor instead.
func (*ListPrepaidBalanceChangesResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{25}
}

func (x *ListPrepaidBalanceChangesResp) GetChanges() []*PrepaidBalanceChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ListPrepaidBalanceChangesResp) GetTotal() *billing.Cent {
	if x != nil {
		return x.Total
	}
	return nil
}

// Top up prepaid credit request.
type TopUpOrGetExistingPendingChangeReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID of the team to top up for.
	TeamId string `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Amount of prepaid credit to top up. Can be any integer and we will disregard the sign.
	Amount        *billing.Cent `protobuf:"bytes,20,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpOrGetExistingPendingChangeReq) Reset() {
	*x = TopUpOrGetExistingPendingChangeReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpOrGetExistingPendingChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpOrGetExistingPendingChangeReq) ProtoMessage() {}

func (x *TopUpOrGetExistingPendingChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpOrGetExistingPendingChangeReq.ProtoReflect.Descriptor instead.
func (*TopUpOrGetExistingPendingChangeReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{26}
}

func (x *TopUpOrGetExistingPendingChangeReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TopUpOrGetExistingPendingChangeReq) GetAmount() *billing.Cent {
	if x != nil {
		return x.Amount
	}
	return nil
}

// Response for prepaid credit top up.
type TopUpOrGetExistingPendingChangeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        *PrepaidBalanceChange  `protobuf:"bytes,10,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpOrGetExistingPendingChangeResp) Reset() {
	*x = TopUpOrGetExistingPendingChangeResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpOrGetExistingPendingChangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpOrGetExistingPendingChangeResp) ProtoMessage() {}

func (x *TopUpOrGetExistingPendingChangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpOrGetExistingPendingChangeResp.ProtoReflect.Descriptor instead.
func (*TopUpOrGetExistingPendingChangeResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{27}
}

func (x *TopUpOrGetExistingPendingChangeResp) GetChange() *PrepaidBalanceChange {
	if x != nil {
		return x.Change
	}
	return nil
}

// Request to get postpaid monthly spending limit.
type GetSpendingLimitsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpendingLimitsReq) Reset() {
	*x = GetSpendingLimitsReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingLimitsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingLimitsReq) ProtoMessage() {}

func (x *GetSpendingLimitsReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingLimitsReq.ProtoReflect.Descriptor instead.
func (*GetSpendingLimitsReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{28}
}

func (x *GetSpendingLimitsReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Postpaid monthly spending limit.
type SpendingLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional spending limit override set by xAI staff.
	HardSlOverride *billing.Cent `protobuf:"bytes,1,opt,name=hard_sl_override,json=hardSlOverride,proto3,oneof" json:"hard_sl_override,omitempty"`
	// Automatically calculated hard spending limit (the maximum monthly invoiced spending limit that can be set by the
	// user).
	HardSlAuto *billing.Cent `protobuf:"bytes,2,opt,name=hard_sl_auto,json=hardSlAuto,proto3" json:"hard_sl_auto,omitempty"`
	// Effective hard spending limit. Takes into account `hard_sl_override` and `hard_sl_auto`. User can set a soft
	// spending limit lower than this.
	EffectiveHardSl *billing.Cent `protobuf:"bytes,5,opt,name=effective_hard_sl,json=effectiveHardSl,proto3" json:"effective_hard_sl,omitempty"`
	// The soft spending limit previously set by customer. Zero if it has not been set.
	SoftSl *billing.Cent `protobuf:"bytes,3,opt,name=soft_sl,json=softSl,proto3,oneof" json:"soft_sl,omitempty"`
	// Final monthly invoiced spending limit that xAI API will enforce.
	EffectiveSl   *billing.Cent `protobuf:"bytes,4,opt,name=effective_sl,json=effectiveSl,proto3" json:"effective_sl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendingLimits) Reset() {
	*x = SpendingLimits{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendingLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingLimits) ProtoMessage() {}

func (x *SpendingLimits) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingLimits.ProtoReflect.Descriptor instead.
func (*SpendingLimits) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{29}
}

func (x *SpendingLimits) GetHardSlOverride() *billing.Cent {
	if x != nil {
		return x.HardSlOverride
	}
	return nil
}

func (x *SpendingLimits) GetHardSlAuto() *billing.Cent {
	if x != nil {
		return x.HardSlAuto
	}
	return nil
}

func (x *SpendingLimits) GetEffectiveHardSl() *billing.Cent {
	if x != nil {
		return x.EffectiveHardSl
	}
	return nil
}

func (x *SpendingLimits) GetSoftSl() *billing.Cent {
	if x != nil {
		return x.SoftSl
	}
	return nil
}

func (x *SpendingLimits) GetEffectiveSl() *billing.Cent {
	if x != nil {
		return x.EffectiveSl
	}
	return nil
}

// Response for postpaid monthly spending limit.
type GetSpendingLimitsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpendingLimits *SpendingLimits        `protobuf:"bytes,1,opt,name=spending_limits,json=spendingLimits,proto3" json:"spending_limits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSpendingLimitsResp) Reset() {
	*x = GetSpendingLimitsResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingLimitsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingLimitsResp) ProtoMessage() {}

func (x *GetSpendingLimitsResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingLimitsResp.ProtoReflect.Descriptor instead.
func (*GetSpendingLimitsResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{30}
}

func (x *GetSpendingLimitsResp) GetSpendingLimits() *SpendingLimits {
	if x != nil {
		return x.SpendingLimits
	}
	return nil
}

// Request by user to set a new postpaid monthly spending limit.
type SetSoftSpendingLimitReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Team ID.
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Desired spending limit in USD cents.
	DesiredSoftSpendingLimit *billing.Cent `protobuf:"bytes,2,opt,name=desired_soft_spending_limit,json=desiredSoftSpendingLimit,proto3" json:"desired_soft_spending_limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SetSoftSpendingLimitReq) Reset() {
	*x = SetSoftSpendingLimitReq{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSoftSpendingLimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSoftSpendingLimitReq) ProtoMessage() {}

func (x *SetSoftSpendingLimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSoftSpendingLimitReq.ProtoReflect.Descriptor instead.
func (*SetSoftSpendingLimitReq) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{31}
}

func (x *SetSoftSpendingLimitReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SetSoftSpendingLimitReq) GetDesiredSoftSpendingLimit() *billing.Cent {
	if x != nil {
		return x.DesiredSoftSpendingLimit
	}
	return nil
}

// Response of setting a new postpaid monthly spending limit.
type SetSoftSpendingLimitResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new spending limit in USD cents.
	ThisBpSoftSpendingLimit *billing.Cent `protobuf:"bytes,1,opt,name=this_bp_soft_spending_limit,json=thisBpSoftSpendingLimit,proto3" json:"this_bp_soft_spending_limit,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetSoftSpendingLimitResp) Reset() {
	*x = SetSoftSpendingLimitResp{}
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSoftSpendingLimitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSoftSpendingLimitResp) ProtoMessage() {}

func (x *SetSoftSpendingLimitResp) ProtoReflect() protoreflect.Message {
	mi := &file_xai_management_api_v1_billing_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSoftSpendingLimitResp.ProtoReflect.Descriptor instead.
func (*SetSoftSpendingLimitResp) Descriptor() ([]byte, []int) {
	return file_xai_management_api_v1_billing_proto_rawDescGZIP(), []int{32}
}

func (x *SetSoftSpendingLimitResp) GetThisBpSoftSpendingLimit() *billing.Cent {
	if x != nil {
		return x.ThisBpSoftSpendingLimit
	}
	return nil
}

var File_xai_management_api_v1_billing_proto protoreflect.FileDescriptor

const file_xai_management_api_v1_billing_proto_rawDesc = "" +
	"\n" +
	"#xai/management_api/v1/billing.proto\x12\x0fprod_mc_billing\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$xai/shared/analytics/analytics.proto\x1a\x1exai/shared/billing/types.proto\"j\n" +
	"\x11SetBillingInfoReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12<\n" +
	"\fbilling_info\x18\n" +
	" \x01(\v2\x19.prod_charger.BillingInfoR\vbillingInfo\"\x14\n" +
	"\x12SetBillingInfoResp\",\n" +
	"\x11GetBillingInfoReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"R\n" +
	"\x12GetBillingInfoResp\x12<\n" +
	"\fbilling_info\x18\n" +
	" \x01(\v2\x19.prod_charger.BillingInfoR\vbillingInfo\"0\n" +
	"\x15ListPaymentMethodsReq\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\"n\n" +
	"\x14PendingPaymentMethod\x12V\n" +
	"(ach_microdeposit_hosted_verification_url\x18\n" +
	" \x01(\tR$achMicrodepositHostedVerificationUrl\"\xc1\x01\n" +
	"\x16ListPaymentMethodsResp\x12D\n" +
	"\x0fpayment_methods\x18\n" +
	" \x03(\v2\x1b.prod_charger.PaymentMethodR\x0epaymentMethods\x12[\n" +
	"\x16pending_payment_method\x18\x15 \x01(\v2%.prod_mc_billing.PendingPaymentMethodR\x14pendingPaymentMethodJ\x04\b\x14\x10\x15\"a\n" +
	"\x1aSetDefaultPaymentMethodReq\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\x12*\n" +
	"\x11payment_method_id\x18\x14 \x01(\tR\x0fpaymentMethodId\"\x1d\n" +
	"\x1bSetDefaultPaymentMethodResp\"\xbc\x01\n" +
	"\x04Line\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tunit_type\x18\x03 \x01(\tR\bunitType\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x03R\tunitPrice\x12\x1b\n" +
	"\tnum_units\x18\x05 \x01(\x03R\bnumUnits\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\"\xd0\x03\n" +
	"\vCoreInvoice\x12+\n" +
	"\x05lines\x18\x01 \x03(\v2\x15.prod_mc_billing.LineR\x05lines\x12*\n" +
	"\x11amount_before_vat\x18\x02 \x01(\x03R\x0famountBeforeVat\x12\x19\n" +
	"\bvat_cost\x18\x03 \x01(\x03R\avatCost\x12(\n" +
	"\x10amount_after_vat\x18\x04 \x01(\x03R\x0eamountAfterVat\x12.\n" +
	"\x13auto_credits_issued\x18\x05 \x01(\x03R\x11autoCreditsIssued\x124\n" +
	"\x16default_credits_issued\x18\x06 \x01(\x03R\x14defaultCreditsIssued\x12:\n" +
	"\x0ftotal_with_corr\x18\t \x01(\v2\x12.prod_charger.CentR\rtotalWithCorr\x12;\n" +
	"\x0fprepaid_credits\x18\b \x01(\v2\x12.prod_charger.CentR\x0eprepaidCredits\x12D\n" +
	"\x14prepaid_credits_used\x18\a \x01(\v2\x12.prod_charger.CentR\x12prepaidCreditsUsed\",\n" +
	"\x11GetAmountToPayReq\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\"\x88\x02\n" +
	"\x12GetAmountToPayResp\x12?\n" +
	"\fcore_invoice\x18\x01 \x01(\v2\x1c.prod_mc_billing.CoreInvoiceR\vcoreInvoice\x128\n" +
	"\x18effective_spending_limit\x18\x02 \x01(\x03R\x16effectiveSpendingLimit\x12'\n" +
	"\x0fdefault_credits\x18\x03 \x01(\x03R\x0edefaultCredits\x12B\n" +
	"\rbilling_cycle\x18\x04 \x01(\v2\x1d.prod_mc_billing.BillingCycleR\fbillingCycleJ\x04\b\n" +
	"\x10\vJ\x04\b\x14\x10\x15\"\x8f\x01\n" +
	"\x1aAnalyzeBillingItemsRequest\x12X\n" +
	"\x11analytics_request\x18\x01 \x01(\v2+.prod.clickhouse_analytics.AnalyticsRequestR\x10analyticsRequest\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"8\n" +
	"\fBillingCycle\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"t\n" +
	"\x0eChargerAttempt\x12\x16\n" +
	"\x06ticket\x18\n" +
	" \x01(\x05R\x06ticket\x12\x1e\n" +
	"\n" +
	"successful\x18\x14 \x01(\bR\n" +
	"successful\x12*\n" +
	"\x11payment_method_id\x18\x1e \x01(\tR\x0fpaymentMethodId\"\x9c\x04\n" +
	"\x14MonthlyInvoiceBundle\x12B\n" +
	"\rbilling_cycle\x18\n" +
	" \x01(\v2\x1d.prod_mc_billing.BillingCycleR\fbillingCycle\x12H\n" +
	"\x16default_credits_issued\x18\x14 \x01(\v2\x12.prod_charger.CentR\x14defaultCreditsIssued\x12B\n" +
	"\x13auto_credits_issued\x18\x1e \x01(\v2\x12.prod_charger.CentR\x11autoCreditsIssued\x12I\n" +
	"\x17prepaid_tokens_to_spend\x18# \x01(\v2\x12.prod_charger.CentR\x14prepaidTokensToSpend\x12N\n" +
	"\"billing_items_csv_asset_key_suffix\x18( \x01(\tH\x00R\x1dbillingItemsCsvAssetKeySuffix\x88\x01\x01\x12K\n" +
	" corrections_csv_asset_key_suffix\x182 \x01(\tH\x01R\x1ccorrectionsCsvAssetKeySuffix\x88\x01\x01B%\n" +
	"#_billing_items_csv_asset_key_suffixB#\n" +
	"!_corrections_csv_asset_key_suffix\"\x16\n" +
	"\x14PrepaidInvoiceBundle\"\x1c\n" +
	"\x1aSubscriptionsInvoiceBundle\"\x8d\a\n" +
	"\rInvoiceBundle\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x14 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0einvoice_number\x18\x15 \x01(\tR\rinvoiceNumber\x12;\n" +
	"\vcreate_time\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12L\n" +
	"\x0einvoice_status\x18( \x01(\x0e2%.prod_mc_billing.InvoiceBundle.StatusR\rinvoiceStatus\x12X\n" +
	"\x1bfirst_desired_next_cycle_ts\x182 \x01(\v2\x1a.google.protobuf.TimestampR\x17firstDesiredNextCycleTs\x12J\n" +
	"\x10charger_attempts\x18< \x03(\v2\x1f.prod_mc_billing.ChargerAttemptR\x0fchargerAttempts\x12+\n" +
	"\x05lines\x18F \x03(\v2\x15.prod_mc_billing.LineR\x05lines\x12\x1a\n" +
	"\bsubtotal\x18P \x01(\x03R\bsubtotal\x12\x10\n" +
	"\x03tax\x18Z \x01(\x03R\x03tax\x12\x14\n" +
	"\x05total\x18d \x01(\x03R\x05total\x12>\n" +
	"\x1cinvoice_pdf_asset_key_suffix\x18n \x01(\tR\x18invoicePdfAssetKeySuffix\x12A\n" +
	"\amonthly\x18x \x01(\v2%.prod_mc_billing.MonthlyInvoiceBundleH\x00R\amonthly\x12B\n" +
	"\aprepaid\x18\x82\x01 \x01(\v2%.prod_mc_billing.PrepaidInvoiceBundleH\x00R\aprepaid\x12T\n" +
	"\rsubscriptions\x18\x8c\x01 \x01(\v2+.prod_mc_billing.SubscriptionsInvoiceBundleH\x00R\rsubscriptions\"S\n" +
	"\x06Status\x12\v\n" +
	"\aINVALID\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\x19\n" +
	"\x15WILL_NEVER_BE_CHARGED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B\t\n" +
	"\aflavour\"-\n" +
	"\n" +
	"InvoiceIds\x12\x1f\n" +
	"\vinvoice_ids\x18\n" +
	" \x03(\tR\n" +
	"invoiceIds\"\xf1\x01\n" +
	"\x0fListInvoicesReq\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\x12D\n" +
	"\rbilling_cycle\x18\x14 \x01(\v2\x1d.prod_mc_billing.BillingCycleH\x00R\fbillingCycle\x125\n" +
	"\x05since\x18\x1e \x01(\v2\x1d.prod_mc_billing.BillingCycleH\x00R\x05since\x12>\n" +
	"\vinvoice_ids\x18( \x01(\v2\x1b.prod_mc_billing.InvoiceIdsH\x00R\n" +
	"invoiceIdsB\b\n" +
	"\x06filter\"N\n" +
	"\x10ListInvoicesResp\x12:\n" +
	"\binvoices\x18\x01 \x03(\v2\x1e.prod_mc_billing.InvoiceBundleR\binvoices\"\x96\a\n" +
	"\x14PrepaidBalanceChange\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\x12W\n" +
	"\rchange_origin\x18\x14 \x01(\x0e22.prod_mc_billing.PrepaidBalanceChange.ChangeOriginR\fchangeOrigin\x12Y\n" +
	"\ftopup_status\x18\x1e \x01(\x0e21.prod_mc_billing.PrepaidBalanceChange.TopUpStatusH\x00R\vtopupStatus\x88\x01\x01\x12*\n" +
	"\x06amount\x18( \x01(\v2\x12.prod_charger.CentR\x06amount\x12\"\n" +
	"\n" +
	"invoice_id\x182 \x01(\tH\x01R\tinvoiceId\x88\x01\x01\x12*\n" +
	"\x0einvoice_number\x183 \x01(\tH\x02R\rinvoiceNumber\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18< \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12.\n" +
	"\x11spend_bp_key_year\x18F \x01(\x05H\x03R\x0espendBpKeyYear\x88\x01\x01\x120\n" +
	"\x12spend_bp_key_month\x18P \x01(\x05H\x04R\x0fspendBpKeyMonth\x88\x01\x01\x12<\n" +
	"\tcreate_ts\x18U \x01(\v2\x1a.google.protobuf.TimestampH\x05R\bcreateTs\x88\x01\x01\"S\n" +
	"\fChangeOrigin\x12\x12\n" +
	"\x0eINVALID_ORIGIN\x10\x00\x12\f\n" +
	"\bPURCHASE\x10\n" +
	"\x12\t\n" +
	"\x05SPEND\x10\x14\x12\n" +
	"\n" +
	"\x06REFUND\x10\x1e\x12\n" +
	"\n" +
	"\x06MANUAL\x10(\"\x8e\x01\n" +
	"\vTopUpStatus\x12\x12\n" +
	"\x0eINVALID_STATUS\x10\x00\x12\x17\n" +
	"\x13TO_GENERATE_INVOICE\x10\n" +
	"\x12\x1e\n" +
	"\x1aFAILED_TO_GENERATE_INVOICE\x10\x14\x12\r\n" +
	"\tTO_CHARGE\x10\x1e\x12\x14\n" +
	"\x10FAILED_TO_CHARGE\x10(\x12\r\n" +
	"\tSUCCEEDED\x102B\x0f\n" +
	"\r_topup_statusB\r\n" +
	"\v_invoice_idB\x11\n" +
	"\x0f_invoice_numberB\x14\n" +
	"\x12_spend_bp_key_yearB\x15\n" +
	"\x13_spend_bp_key_monthB\f\n" +
	"\n" +
	"_create_tsJ\x04\bZ\x10[\"7\n" +
	"\x1cListPrepaidBalanceChangesReq\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\"\x8a\x01\n" +
	"\x1dListPrepaidBalanceChangesResp\x12?\n" +
	"\achanges\x18\n" +
	" \x03(\v2%.prod_mc_billing.PrepaidBalanceChangeR\achanges\x12(\n" +
	"\x05total\x18\x14 \x01(\v2\x12.prod_charger.CentR\x05total\"i\n" +
	"\"TopUpOrGetExistingPendingChangeReq\x12\x17\n" +
	"\ateam_id\x18\n" +
	" \x01(\tR\x06teamId\x12*\n" +
	"\x06amount\x18\x14 \x01(\v2\x12.prod_charger.CentR\x06amount\"d\n" +
	"#TopUpOrGetExistingPendingChangeResp\x12=\n" +
	"\x06change\x18\n" +
	" \x01(\v2%.prod_mc_billing.PrepaidBalanceChangeR\x06change\"/\n" +
	"\x14GetSpendingLimitsReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\xd3\x02\n" +
	"\x0eSpendingLimits\x12A\n" +
	"\x10hard_sl_override\x18\x01 \x01(\v2\x12.prod_charger.CentH\x00R\x0ehardSlOverride\x88\x01\x01\x124\n" +
	"\fhard_sl_auto\x18\x02 \x01(\v2\x12.prod_charger.CentR\n" +
	"hardSlAuto\x12>\n" +
	"\x11effective_hard_sl\x18\x05 \x01(\v2\x12.prod_charger.CentR\x0feffectiveHardSl\x120\n" +
	"\asoft_sl\x18\x03 \x01(\v2\x12.prod_charger.CentH\x01R\x06softSl\x88\x01\x01\x125\n" +
	"\feffective_sl\x18\x04 \x01(\v2\x12.prod_charger.CentR\veffectiveSlB\x13\n" +
	"\x11_hard_sl_overrideB\n" +
	"\n" +
	"\b_soft_sl\"a\n" +
	"\x15GetSpendingLimitsResp\x12H\n" +
	"\x0fspending_limits\x18\x01 \x01(\v2\x1f.prod_mc_billing.SpendingLimitsR\x0espendingLimits\"\x85\x01\n" +
	"\x17SetSoftSpendingLimitReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12Q\n" +
	"\x1bdesired_soft_spending_limit\x18\x02 \x01(\v2\x12.prod_charger.CentR\x18desiredSoftSpendingLimit\"l\n" +
	"\x18SetSoftSpendingLimitResp\x12P\n" +
	"\x1bthis_bp_soft_spending_limit\x18\x01 \x01(\v2\x12.prod_charger.CentR\x17thisBpSoftSpendingLimit2\xae\t\n" +
	"\x05UISvc\x12[\n" +
	"\x0eSetBillingInfo\x12\".prod_mc_billing.SetBillingInfoReq\x1a#.prod_mc_billing.SetBillingInfoResp\"\x00\x12[\n" +
	"\x0eGetBillingInfo\x12\".prod_mc_billing.GetBillingInfoReq\x1a#.prod_mc_billing.GetBillingInfoResp\"\x00\x12g\n" +
	"\x12ListPaymentMethods\x12&.prod_mc_billing.ListPaymentMethodsReq\x1a'.prod_mc_billing.ListPaymentMethodsResp\"\x00\x12v\n" +
	"\x17SetDefaultPaymentMethod\x12+.prod_mc_billing.SetDefaultPaymentMethodReq\x1a,.prod_mc_billing.SetDefaultPaymentMethodResp\"\x00\x12[\n" +
	"\x0eGetAmountToPay\x12\".prod_mc_billing.GetAmountToPayReq\x1a#.prod_mc_billing.GetAmountToPayResp\"\x00\x12r\n" +
	"\x13AnalyzeBillingItems\x12+.prod_mc_billing.AnalyzeBillingItemsRequest\x1a,.prod.clickhouse_analytics.AnalyticsResponse\"\x00\x12U\n" +
	"\fListInvoices\x12 .prod_mc_billing.ListInvoicesReq\x1a!.prod_mc_billing.ListInvoicesResp\"\x00\x12|\n" +
	"\x19ListPrepaidBalanceChanges\x12-.prod_mc_billing.ListPrepaidBalanceChangesReq\x1a..prod_mc_billing.ListPrepaidBalanceChangesResp\"\x00\x12\x8e\x01\n" +
	"\x1fTopUpOrGetExistingPendingChange\x123.prod_mc_billing.TopUpOrGetExistingPendingChangeReq\x1a4.prod_mc_billing.TopUpOrGetExistingPendingChangeResp\"\x00\x12d\n" +
	"\x11GetSpendingLimits\x12%.prod_mc_billing.GetSpendingLimitsReq\x1a&.prod_mc_billing.GetSpendingLimitsResp\"\x00\x12m\n" +
	"\x14SetSoftSpendingLimit\x12(.prod_mc_billing.SetSoftSpendingLimitReq\x1a).prod_mc_billing.SetSoftSpendingLimitResp\"\x00B\xab\x01\n" +
	"\x13com.prod_mc_billingB\fBillingProtoP\x01Z2github.com/zchee/tumix/model/xai/management_api/v1\xa2\x02\x03PXX\xaa\x02\rProdMcBilling\xca\x02\rProdMcBilling\xe2\x02\x19ProdMcBilling\\GPBMetadata\xea\x02\rProdMcBillingb\x06proto3"

var (
	file_xai_management_api_v1_billing_proto_rawDescOnce sync.Once
	file_xai_management_api_v1_billing_proto_rawDescData []byte
)

func file_xai_management_api_v1_billing_proto_rawDescGZIP() []byte {
	file_xai_management_api_v1_billing_proto_rawDescOnce.Do(func() {
		file_xai_management_api_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xai_management_api_v1_billing_proto_rawDesc), len(file_xai_management_api_v1_billing_proto_rawDesc)))
	})
	return file_xai_management_api_v1_billing_proto_rawDescData
}

var file_xai_management_api_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_xai_management_api_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_xai_management_api_v1_billing_proto_goTypes = []any{
	(InvoiceBundle_Status)(0),                   // 0: prod_mc_billing.InvoiceBundle.Status
	(PrepaidBalanceChange_ChangeOrigin)(0),      // 1: prod_mc_billing.PrepaidBalanceChange.ChangeOrigin
	(PrepaidBalanceChange_TopUpStatus)(0),       // 2: prod_mc_billing.PrepaidBalanceChange.TopUpStatus
	(*SetBillingInfoReq)(nil),                   // 3: prod_mc_billing.SetBillingInfoReq
	(*SetBillingInfoResp)(nil),                  // 4: prod_mc_billing.SetBillingInfoResp
	(*GetBillingInfoReq)(nil),                   // 5: prod_mc_billing.GetBillingInfoReq
	(*GetBillingInfoResp)(nil),                  // 6: prod_mc_billing.GetBillingInfoResp
	(*ListPaymentMethodsReq)(nil),               // 7: prod_mc_billing.ListPaymentMethodsReq
	(*PendingPaymentMethod)(nil),                // 8: prod_mc_billing.PendingPaymentMethod
	(*ListPaymentMethodsResp)(nil),              // 9: prod_mc_billing.ListPaymentMethodsResp
	(*SetDefaultPaymentMethodReq)(nil),          // 10: prod_mc_billing.SetDefaultPaymentMethodReq
	(*SetDefaultPaymentMethodResp)(nil),         // 11: prod_mc_billing.SetDefaultPaymentMethodResp
	(*Line)(nil),                                // 12: prod_mc_billing.Line
	(*CoreInvoice)(nil),                         // 13: prod_mc_billing.CoreInvoice
	(*GetAmountToPayReq)(nil),                   // 14: prod_mc_billing.GetAmountToPayReq
	(*GetAmountToPayResp)(nil),                  // 15: prod_mc_billing.GetAmountToPayResp
	(*AnalyzeBillingItemsRequest)(nil),          // 16: prod_mc_billing.AnalyzeBillingItemsRequest
	(*BillingCycle)(nil),                        // 17: prod_mc_billing.BillingCycle
	(*ChargerAttempt)(nil),                      // 18: prod_mc_billing.ChargerAttempt
	(*MonthlyInvoiceBundle)(nil),                // 19: prod_mc_billing.MonthlyInvoiceBundle
	(*PrepaidInvoiceBundle)(nil),                // 20: prod_mc_billing.PrepaidInvoiceBundle
	(*SubscriptionsInvoiceBundle)(nil),          // 21: prod_mc_billing.SubscriptionsInvoiceBundle
	(*InvoiceBundle)(nil),                       // 22: prod_mc_billing.InvoiceBundle
	(*InvoiceIds)(nil),                          // 23: prod_mc_billing.InvoiceIds
	(*ListInvoicesReq)(nil),                     // 24: prod_mc_billing.ListInvoicesReq
	(*ListInvoicesResp)(nil),                    // 25: prod_mc_billing.ListInvoicesResp
	(*PrepaidBalanceChange)(nil),                // 26: prod_mc_billing.PrepaidBalanceChange
	(*ListPrepaidBalanceChangesReq)(nil),        // 27: prod_mc_billing.ListPrepaidBalanceChangesReq
	(*ListPrepaidBalanceChangesResp)(nil),       // 28: prod_mc_billing.ListPrepaidBalanceChangesResp
	(*TopUpOrGetExistingPendingChangeReq)(nil),  // 29: prod_mc_billing.TopUpOrGetExistingPendingChangeReq
	(*TopUpOrGetExistingPendingChangeResp)(nil), // 30: prod_mc_billing.TopUpOrGetExistingPendingChangeResp
	(*GetSpendingLimitsReq)(nil),                // 31: prod_mc_billing.GetSpendingLimitsReq
	(*SpendingLimits)(nil),                      // 32: prod_mc_billing.SpendingLimits
	(*GetSpendingLimitsResp)(nil),               // 33: prod_mc_billing.GetSpendingLimitsResp
	(*SetSoftSpendingLimitReq)(nil),             // 34: prod_mc_billing.SetSoftSpendingLimitReq
	(*SetSoftSpendingLimitResp)(nil),            // 35: prod_mc_billing.SetSoftSpendingLimitResp
	(*billing.BillingInfo)(nil),                 // 36: prod_charger.BillingInfo
	(*billing.PaymentMethod)(nil),               // 37: prod_charger.PaymentMethod
	(*billing.Cent)(nil),                        // 38: prod_charger.Cent
	(*analytics.AnalyticsRequest)(nil),          // 39: prod.clickhouse_analytics.AnalyticsRequest
	(*timestamppb.Timestamp)(nil),               // 40: google.protobuf.Timestamp
	(*analytics.AnalyticsResponse)(nil),         // 41: prod.clickhouse_analytics.AnalyticsResponse
}
var file_xai_management_api_v1_billing_proto_depIdxs = []int32{
	36, // 0: prod_mc_billing.SetBillingInfoReq.billing_info:type_name -> prod_charger.BillingInfo
	36, // 1: prod_mc_billing.GetBillingInfoResp.billing_info:type_name -> prod_charger.BillingInfo
	37, // 2: prod_mc_billing.ListPaymentMethodsResp.payment_methods:type_name -> prod_charger.PaymentMethod
	8,  // 3: prod_mc_billing.ListPaymentMethodsResp.pending_payment_method:type_name -> prod_mc_billing.PendingPaymentMethod
	12, // 4: prod_mc_billing.CoreInvoice.lines:type_name -> prod_mc_billing.Line
	38, // 5: prod_mc_billing.CoreInvoice.total_with_corr:type_name -> prod_charger.Cent
	38, // 6: prod_mc_billing.CoreInvoice.prepaid_credits:type_name -> prod_charger.Cent
	38, // 7: prod_mc_billing.CoreInvoice.prepaid_credits_used:type_name -> prod_charger.Cent
	13, // 8: prod_mc_billing.GetAmountToPayResp.core_invoice:type_name -> prod_mc_billing.CoreInvoice
	17, // 9: prod_mc_billing.GetAmountToPayResp.billing_cycle:type_name -> prod_mc_billing.BillingCycle
	39, // 10: prod_mc_billing.AnalyzeBillingItemsRequest.analytics_request:type_name -> prod.clickhouse_analytics.AnalyticsRequest
	17, // 11: prod_mc_billing.MonthlyInvoiceBundle.billing_cycle:type_name -> prod_mc_billing.BillingCycle
	38, // 12: prod_mc_billing.MonthlyInvoiceBundle.default_credits_issued:type_name -> prod_charger.Cent
	38, // 13: prod_mc_billing.MonthlyInvoiceBundle.auto_credits_issued:type_name -> prod_charger.Cent
	38, // 14: prod_mc_billing.MonthlyInvoiceBundle.prepaid_tokens_to_spend:type_name -> prod_charger.Cent
	40, // 15: prod_mc_billing.InvoiceBundle.create_time:type_name -> google.protobuf.Timestamp
	0,  // 16: prod_mc_billing.InvoiceBundle.invoice_status:type_name -> prod_mc_billing.InvoiceBundle.Status
	40, // 17: prod_mc_billing.InvoiceBundle.first_desired_next_cycle_ts:type_name -> google.protobuf.Timestamp
	18, // 18: prod_mc_billing.InvoiceBundle.charger_attempts:type_name -> prod_mc_billing.ChargerAttempt
	12, // 19: prod_mc_billing.InvoiceBundle.lines:type_name -> prod_mc_billing.Line
	19, // 20: prod_mc_billing.InvoiceBundle.monthly:type_name -> prod_mc_billing.MonthlyInvoiceBundle
	20, // 21: prod_mc_billing.InvoiceBundle.prepaid:type_name -> prod_mc_billing.PrepaidInvoiceBundle
	21, // 22: prod_mc_billing.InvoiceBundle.subscriptions:type_name -> prod_mc_billing.SubscriptionsInvoiceBundle
	17, // 23: prod_mc_billing.ListInvoicesReq.billing_cycle:type_name -> prod_mc_billing.BillingCycle
	17, // 24: prod_mc_billing.ListInvoicesReq.since:type_name -> prod_mc_billing.BillingCycle
	23, // 25: prod_mc_billing.ListInvoicesReq.invoice_ids:type_name -> prod_mc_billing.InvoiceIds
	22, // 26: prod_mc_billing.ListInvoicesResp.invoices:type_name -> prod_mc_billing.InvoiceBundle
	1,  // 27: prod_mc_billing.PrepaidBalanceChange.change_origin:type_name -> prod_mc_billing.PrepaidBalanceChange.ChangeOrigin
	2,  // 28: prod_mc_billing.PrepaidBalanceChange.topup_status:type_name -> prod_mc_billing.PrepaidBalanceChange.TopUpStatus
	38, // 29: prod_mc_billing.PrepaidBalanceChange.amount:type_name -> prod_charger.Cent
	40, // 30: prod_mc_billing.PrepaidBalanceChange.create_time:type_name -> google.protobuf.Timestamp
	40, // 31: prod_mc_billing.PrepaidBalanceChange.create_ts:type_name -> google.protobuf.Timestamp
	26, // 32: prod_mc_billing.ListPrepaidBalanceChangesResp.changes:type_name -> prod_mc_billing.PrepaidBalanceChange
	38, // 33: prod_mc_billing.ListPrepaidBalanceChangesResp.total:type_name -> prod_charger.Cent
	38, // 34: prod_mc_billing.TopUpOrGetExistingPendingChangeReq.amount:type_name -> prod_charger.Cent
	26, // 35: prod_mc_billing.TopUpOrGetExistingPendingChangeResp.change:type_name -> prod_mc_billing.PrepaidBalanceChange
	38, // 36: prod_mc_billing.SpendingLimits.hard_sl_override:type_name -> prod_charger.Cent
	38, // 37: prod_mc_billing.SpendingLimits.hard_sl_auto:type_name -> prod_charger.Cent
	38, // 38: prod_mc_billing.SpendingLimits.effective_hard_sl:type_name -> prod_charger.Cent
	38, // 39: prod_mc_billing.SpendingLimits.soft_sl:type_name -> prod_charger.Cent
	38, // 40: prod_mc_billing.SpendingLimits.effective_sl:type_name -> prod_charger.Cent
	32, // 41: prod_mc_billing.GetSpendingLimitsResp.spending_limits:type_name -> prod_mc_billing.SpendingLimits
	38, // 42: prod_mc_billing.SetSoftSpendingLimitReq.desired_soft_spending_limit:type_name -> prod_charger.Cent
	38, // 43: prod_mc_billing.SetSoftSpendingLimitResp.this_bp_soft_spending_limit:type_name -> prod_charger.Cent
	3,  // 44: prod_mc_billing.UISvc.SetBillingInfo:input_type -> prod_mc_billing.SetBillingInfoReq
	5,  // 45: prod_mc_billing.UISvc.GetBillingInfo:input_type -> prod_mc_billing.GetBillingInfoReq
	7,  // 46: prod_mc_billing.UISvc.ListPaymentMethods:input_type -> prod_mc_billing.ListPaymentMethodsReq
	10, // 47: prod_mc_billing.UISvc.SetDefaultPaymentMethod:input_type -> prod_mc_billing.SetDefaultPaymentMethodReq
	14, // 48: prod_mc_billing.UISvc.GetAmountToPay:input_type -> prod_mc_billing.GetAmountToPayReq
	16, // 49: prod_mc_billing.UISvc.AnalyzeBillingItems:input_type -> prod_mc_billing.AnalyzeBillingItemsRequest
	24, // 50: prod_mc_billing.UISvc.ListInvoices:input_type -> prod_mc_billing.ListInvoicesReq
	27, // 51: prod_mc_billing.UISvc.ListPrepaidBalanceChanges:input_type -> prod_mc_billing.ListPrepaidBalanceChangesReq
	29, // 52: prod_mc_billing.UISvc.TopUpOrGetExistingPendingChange:input_type -> prod_mc_billing.TopUpOrGetExistingPendingChangeReq
	31, // 53: prod_mc_billing.UISvc.GetSpendingLimits:input_type -> prod_mc_billing.GetSpendingLimitsReq
	34, // 54: prod_mc_billing.UISvc.SetSoftSpendingLimit:input_type -> prod_mc_billing.SetSoftSpendingLimitReq
	4,  // 55: prod_mc_billing.UISvc.SetBillingInfo:output_type -> prod_mc_billing.SetBillingInfoResp
	6,  // 56: prod_mc_billing.UISvc.GetBillingInfo:output_type -> prod_mc_billing.GetBillingInfoResp
	9,  // 57: prod_mc_billing.UISvc.ListPaymentMethods:output_type -> prod_mc_billing.ListPaymentMethodsResp
	11, // 58: prod_mc_billing.UISvc.SetDefaultPaymentMethod:output_type -> prod_mc_billing.SetDefaultPaymentMethodResp
	15, // 59: prod_mc_billing.UISvc.GetAmountToPay:output_type -> prod_mc_billing.GetAmountToPayResp
	41, // 60: prod_mc_billing.UISvc.AnalyzeBillingItems:output_type -> prod.clickhouse_analytics.AnalyticsResponse
	25, // 61: prod_mc_billing.UISvc.ListInvoices:output_type -> prod_mc_billing.ListInvoicesResp
	28, // 62: prod_mc_billing.UISvc.ListPrepaidBalanceChanges:output_type -> prod_mc_billing.ListPrepaidBalanceChangesResp
	30, // 63: prod_mc_billing.UISvc.TopUpOrGetExistingPendingChange:output_type -> prod_mc_billing.TopUpOrGetExistingPendingChangeResp
	33, // 64: prod_mc_billing.UISvc.GetSpendingLimits:output_type -> prod_mc_billing.GetSpendingLimitsResp
	35, // 65: prod_mc_billing.UISvc.SetSoftSpendingLimit:output_type -> prod_mc_billing.SetSoftSpendingLimitResp
	55, // [55:66] is the sub-list for method output_type
	44, // [44:55] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_xai_management_api_v1_billing_proto_init() }
func file_xai_management_api_v1_billing_proto_init() {
	if File_xai_management_api_v1_billing_proto != nil {
		return
	}
	file_xai_management_api_v1_billing_proto_msgTypes[16].OneofWrappers = []any{}
	file_xai_management_api_v1_billing_proto_msgTypes[19].OneofWrappers = []any{
		(*InvoiceBundle_Monthly)(nil),
		(*InvoiceBundle_Prepaid)(nil),
		(*InvoiceBundle_Subscriptions)(nil),
	}
	file_xai_management_api_v1_billing_proto_msgTypes[21].OneofWrappers = []any{
		(*ListInvoicesReq_BillingCycle)(nil),
		(*ListInvoicesReq_Since)(nil),
		(*ListInvoicesReq_InvoiceIds)(nil),
	}
	file_xai_management_api_v1_billing_proto_msgTypes[23].OneofWrappers = []any{}
	file_xai_management_api_v1_billing_proto_msgTypes[29].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xai_management_api_v1_billing_proto_rawDesc), len(file_xai_management_api_v1_billing_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xai_management_api_v1_billing_proto_goTypes,
		DependencyIndexes: file_xai_management_api_v1_billing_proto_depIdxs,
		EnumInfos:         file_xai_management_api_v1_billing_proto_enumTypes,
		MessageInfos:      file_xai_management_api_v1_billing_proto_msgTypes,
	}.Build()
	File_xai_management_api_v1_billing_proto = out.File
	file_xai_management_api_v1_billing_proto_goTypes = nil
	file_xai_management_api_v1_billing_proto_depIdxs = nil
}
