// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: xai/shared/billing/types.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment method types.
type PaymentMethodType int32

const (
	PaymentMethodType_UNKNOWN_PMT     PaymentMethodType = 0
	PaymentMethodType_CARD            PaymentMethodType = 10
	PaymentMethodType_CASHAPP         PaymentMethodType = 20
	PaymentMethodType_LINK            PaymentMethodType = 30
	PaymentMethodType_US_BANK_ACCOUNT PaymentMethodType = 40
)

// Enum value maps for PaymentMethodType.
var (
	PaymentMethodType_name = map[int32]string{
		0:  "UNKNOWN_PMT",
		10: "CARD",
		20: "CASHAPP",
		30: "LINK",
		40: "US_BANK_ACCOUNT",
	}
	PaymentMethodType_value = map[string]int32{
		"UNKNOWN_PMT":     0,
		"CARD":            10,
		"CASHAPP":         20,
		"LINK":            30,
		"US_BANK_ACCOUNT": 40,
	}
)

func (x PaymentMethodType) Enum() *PaymentMethodType {
	p := new(PaymentMethodType)
	*p = x
	return p
}

func (x PaymentMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_shared_billing_types_proto_enumTypes[0].Descriptor()
}

func (PaymentMethodType) Type() protoreflect.EnumType {
	return &file_xai_shared_billing_types_proto_enumTypes[0]
}

func (x PaymentMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodType.Descriptor instead.
func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{0}
}

// Representation of USD Cents.
type Cent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cent) Reset() {
	*x = Cent{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cent) ProtoMessage() {}

func (x *Cent) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cent.ProtoReflect.Descriptor instead.
func (*Cent) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{0}
}

func (x *Cent) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

// Payment method types wrapper to allow repeated optional fields.
type PaymentMethodTypes struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodTypes []PaymentMethodType    `protobuf:"varint,1,rep,packed,name=payment_method_types,json=paymentMethodTypes,proto3,enum=prod_charger.PaymentMethodType" json:"payment_method_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PaymentMethodTypes) Reset() {
	*x = PaymentMethodTypes{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethodTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodTypes) ProtoMessage() {}

func (x *PaymentMethodTypes) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodTypes.ProtoReflect.Descriptor instead.
func (*PaymentMethodTypes) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMethodTypes) GetPaymentMethodTypes() []PaymentMethodType {
	if x != nil {
		return x.PaymentMethodTypes
	}
	return nil
}

// A redacted version of card details. The actual card details are handled by third-party payment providers.
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address line 1 (e.g., street, PO Box, or company name).
	Line1 string `protobuf:"bytes,10,opt,name=line1,proto3" json:"line1,omitempty"`
	// Address line 2 (e.g., apartment, suite, unit, or building).
	Line2 string `protobuf:"bytes,11,opt,name=line2,proto3" json:"line2,omitempty"`
	// City, district, suburb, town, or village.
	City string `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	// Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
	Country string `protobuf:"bytes,20,opt,name=country,proto3" json:"country,omitempty"`
	// ZIP or postal code.
	PostalCode string `protobuf:"bytes,30,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// State, county, province, or region.
	State         string `protobuf:"bytes,40,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Billing info.
type BillingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The customer's full name or business name.
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	// The customer's address.
	Address *Address `protobuf:"bytes,20,opt,name=address,proto3" json:"address,omitempty"`
	// The customer's email.
	Email string `protobuf:"bytes,30,opt,name=email,proto3" json:"email,omitempty"`
	// Customer Tax ID type on Stripe ([Stripe Reference](https://docs.stripe.com/api/tax_ids/customer_create))
	TaxIdType string `protobuf:"bytes,40,opt,name=tax_id_type,json=taxIdType,proto3" json:"tax_id_type,omitempty"`
	// Customer Tax ID number on Stripe ([Stripe Reference](https://docs.stripe.com/api/tax_ids/customer_create))
	TaxNumber     string `protobuf:"bytes,41,opt,name=tax_number,json=taxNumber,proto3" json:"tax_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingInfo) Reset() {
	*x = BillingInfo{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingInfo) ProtoMessage() {}

func (x *BillingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingInfo.ProtoReflect.Descriptor instead.
func (*BillingInfo) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{3}
}

func (x *BillingInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BillingInfo) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BillingInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BillingInfo) GetTaxIdType() string {
	if x != nil {
		return x.TaxIdType
	}
	return ""
}

func (x *BillingInfo) GetTaxNumber() string {
	if x != nil {
		return x.TaxNumber
	}
	return ""
}

// A redacted version of card details. The actual card details are handled by third-party payment providers.
type CardDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Card brand.
	// Can be `amex`, `diners`, `discover`, `eftpos_au`, `jcb`, `mastercard`, `unionpay`, `visa`, or `unknown`.
	Brand string `protobuf:"bytes,10,opt,name=brand,proto3" json:"brand,omitempty"`
	// Two-digit number representing the card's expiration month.
	ExpMonth int64 `protobuf:"varint,20,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	// Four-digit number representing the card's expiration year.
	ExpYear int64 `protobuf:"varint,30,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	// The last four digits of the card.
	Last4         string `protobuf:"bytes,40,opt,name=last4,proto3" json:"last4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardDetails) Reset() {
	*x = CardDetails{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDetails) ProtoMessage() {}

func (x *CardDetails) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardDetails.ProtoReflect.Descriptor instead.
func (*CardDetails) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{4}
}

func (x *CardDetails) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CardDetails) GetExpMonth() int64 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *CardDetails) GetExpYear() int64 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *CardDetails) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

// ACH blocked reason.
type UsBankAccountBlocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkCode   string                 `protobuf:"bytes,10,opt,name=network_code,json=networkCode,proto3" json:"network_code,omitempty"`
	BlockReason   string                 `protobuf:"bytes,20,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsBankAccountBlocked) Reset() {
	*x = UsBankAccountBlocked{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsBankAccountBlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsBankAccountBlocked) ProtoMessage() {}

func (x *UsBankAccountBlocked) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsBankAccountBlocked.ProtoReflect.Descriptor instead.
func (*UsBankAccountBlocked) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{5}
}

func (x *UsBankAccountBlocked) GetNetworkCode() string {
	if x != nil {
		return x.NetworkCode
	}
	return ""
}

func (x *UsBankAccountBlocked) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

// ACH details.
type UsBankAccountDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankName      string                 `protobuf:"bytes,10,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	Last4         string                 `protobuf:"bytes,20,opt,name=last4,proto3" json:"last4,omitempty"`
	RoutingNumber string                 `protobuf:"bytes,30,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	Blocked       *UsBankAccountBlocked  `protobuf:"bytes,40,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsBankAccountDetails) Reset() {
	*x = UsBankAccountDetails{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsBankAccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsBankAccountDetails) ProtoMessage() {}

func (x *UsBankAccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsBankAccountDetails.ProtoReflect.Descriptor instead.
func (*UsBankAccountDetails) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{6}
}

func (x *UsBankAccountDetails) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *UsBankAccountDetails) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *UsBankAccountDetails) GetRoutingNumber() string {
	if x != nil {
		return x.RoutingNumber
	}
	return ""
}

func (x *UsBankAccountDetails) GetBlocked() *UsBankAccountBlocked {
	if x != nil {
		return x.Blocked
	}
	return nil
}

// Link payment details.
type LinkDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkDetails) Reset() {
	*x = LinkDetails{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkDetails) ProtoMessage() {}

func (x *LinkDetails) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkDetails.ProtoReflect.Descriptor instead.
func (*LinkDetails) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{7}
}

func (x *LinkDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Payment method and details.
type PaymentMethod struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId      string                 `protobuf:"bytes,10,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	BillingInfo          *BillingInfo           `protobuf:"bytes,20,opt,name=billing_info,json=billingInfo,proto3" json:"billing_info,omitempty"`
	CardDetails          *CardDetails           `protobuf:"bytes,30,opt,name=card_details,json=cardDetails,proto3" json:"card_details,omitempty"`
	UsBankAccountDetails *UsBankAccountDetails  `protobuf:"bytes,31,opt,name=us_bank_account_details,json=usBankAccountDetails,proto3" json:"us_bank_account_details,omitempty"`
	LinkDetails          *LinkDetails           `protobuf:"bytes,32,opt,name=link_details,json=linkDetails,proto3" json:"link_details,omitempty"`
	PaymentType          string                 `protobuf:"bytes,40,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_xai_shared_billing_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_xai_shared_billing_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_xai_shared_billing_types_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentMethod) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *PaymentMethod) GetBillingInfo() *BillingInfo {
	if x != nil {
		return x.BillingInfo
	}
	return nil
}

func (x *PaymentMethod) GetCardDetails() *CardDetails {
	if x != nil {
		return x.CardDetails
	}
	return nil
}

func (x *PaymentMethod) GetUsBankAccountDetails() *UsBankAccountDetails {
	if x != nil {
		return x.UsBankAccountDetails
	}
	return nil
}

func (x *PaymentMethod) GetLinkDetails() *LinkDetails {
	if x != nil {
		return x.LinkDetails
	}
	return nil
}

func (x *PaymentMethod) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

var File_xai_shared_billing_types_proto protoreflect.FileDescriptor

const file_xai_shared_billing_types_proto_rawDesc = "" +
	"\n" +
	"\x1exai/shared/billing/types.proto\x12\fprod_charger\"\x18\n" +
	"\x04Cent\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x03R\x03val\"g\n" +
	"\x12PaymentMethodTypes\x12Q\n" +
	"\x14payment_method_types\x18\x01 \x03(\x0e2\x1f.prod_charger.PaymentMethodTypeR\x12paymentMethodTypes\"\x9a\x01\n" +
	"\aAddress\x12\x14\n" +
	"\x05line1\x18\n" +
	" \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\v \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x0f \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x14 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x1e \x01(\tR\n" +
	"postalCode\x12\x14\n" +
	"\x05state\x18( \x01(\tR\x05state\"\xa7\x01\n" +
	"\vBillingInfo\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12/\n" +
	"\aaddress\x18\x14 \x01(\v2\x15.prod_charger.AddressR\aaddress\x12\x14\n" +
	"\x05email\x18\x1e \x01(\tR\x05email\x12\x1e\n" +
	"\vtax_id_type\x18( \x01(\tR\ttaxIdType\x12\x1d\n" +
	"\n" +
	"tax_number\x18) \x01(\tR\ttaxNumber\"q\n" +
	"\vCardDetails\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\tR\x05brand\x12\x1b\n" +
	"\texp_month\x18\x14 \x01(\x03R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x1e \x01(\x03R\aexpYear\x12\x14\n" +
	"\x05last4\x18( \x01(\tR\x05last4\"\\\n" +
	"\x14UsBankAccountBlocked\x12!\n" +
	"\fnetwork_code\x18\n" +
	" \x01(\tR\vnetworkCode\x12!\n" +
	"\fblock_reason\x18\x14 \x01(\tR\vblockReason\"\xae\x01\n" +
	"\x14UsBankAccountDetails\x12\x1b\n" +
	"\tbank_name\x18\n" +
	" \x01(\tR\bbankName\x12\x14\n" +
	"\x05last4\x18\x14 \x01(\tR\x05last4\x12%\n" +
	"\x0erouting_number\x18\x1e \x01(\tR\rroutingNumber\x12<\n" +
	"\ablocked\x18( \x01(\v2\".prod_charger.UsBankAccountBlockedR\ablocked\"#\n" +
	"\vLinkDetails\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xf3\x02\n" +
	"\rPaymentMethod\x12*\n" +
	"\x11payment_method_id\x18\n" +
	" \x01(\tR\x0fpaymentMethodId\x12<\n" +
	"\fbilling_info\x18\x14 \x01(\v2\x19.prod_charger.BillingInfoR\vbillingInfo\x12<\n" +
	"\fcard_details\x18\x1e \x01(\v2\x19.prod_charger.CardDetailsR\vcardDetails\x12Y\n" +
	"\x17us_bank_account_details\x18\x1f \x01(\v2\".prod_charger.UsBankAccountDetailsR\x14usBankAccountDetails\x12<\n" +
	"\flink_details\x18  \x01(\v2\x19.prod_charger.LinkDetailsR\vlinkDetails\x12!\n" +
	"\fpayment_type\x18( \x01(\tR\vpaymentType*Z\n" +
	"\x11PaymentMethodType\x12\x0f\n" +
	"\vUNKNOWN_PMT\x10\x00\x12\b\n" +
	"\x04CARD\x10\n" +
	"\x12\v\n" +
	"\aCASHAPP\x10\x14\x12\b\n" +
	"\x04LINK\x10\x1e\x12\x13\n" +
	"\x0fUS_BANK_ACCOUNT\x10(B\x9b\x01\n" +
	"\x10com.prod_chargerB\n" +
	"TypesProtoP\x01Z/github.com/zchee/tumix/model/xai/shared/billing\xa2\x02\x03PXX\xaa\x02\vProdCharger\xca\x02\vProdCharger\xe2\x02\x17ProdCharger\\GPBMetadata\xea\x02\vProdChargerb\x06proto3"

var (
	file_xai_shared_billing_types_proto_rawDescOnce sync.Once
	file_xai_shared_billing_types_proto_rawDescData []byte
)

func file_xai_shared_billing_types_proto_rawDescGZIP() []byte {
	file_xai_shared_billing_types_proto_rawDescOnce.Do(func() {
		file_xai_shared_billing_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xai_shared_billing_types_proto_rawDesc), len(file_xai_shared_billing_types_proto_rawDesc)))
	})
	return file_xai_shared_billing_types_proto_rawDescData
}

var file_xai_shared_billing_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xai_shared_billing_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_xai_shared_billing_types_proto_goTypes = []any{
	(PaymentMethodType)(0),       // 0: prod_charger.PaymentMethodType
	(*Cent)(nil),                 // 1: prod_charger.Cent
	(*PaymentMethodTypes)(nil),   // 2: prod_charger.PaymentMethodTypes
	(*Address)(nil),              // 3: prod_charger.Address
	(*BillingInfo)(nil),          // 4: prod_charger.BillingInfo
	(*CardDetails)(nil),          // 5: prod_charger.CardDetails
	(*UsBankAccountBlocked)(nil), // 6: prod_charger.UsBankAccountBlocked
	(*UsBankAccountDetails)(nil), // 7: prod_charger.UsBankAccountDetails
	(*LinkDetails)(nil),          // 8: prod_charger.LinkDetails
	(*PaymentMethod)(nil),        // 9: prod_charger.PaymentMethod
}
var file_xai_shared_billing_types_proto_depIdxs = []int32{
	0, // 0: prod_charger.PaymentMethodTypes.payment_method_types:type_name -> prod_charger.PaymentMethodType
	3, // 1: prod_charger.BillingInfo.address:type_name -> prod_charger.Address
	6, // 2: prod_charger.UsBankAccountDetails.blocked:type_name -> prod_charger.UsBankAccountBlocked
	4, // 3: prod_charger.PaymentMethod.billing_info:type_name -> prod_charger.BillingInfo
	5, // 4: prod_charger.PaymentMethod.card_details:type_name -> prod_charger.CardDetails
	7, // 5: prod_charger.PaymentMethod.us_bank_account_details:type_name -> prod_charger.UsBankAccountDetails
	8, // 6: prod_charger.PaymentMethod.link_details:type_name -> prod_charger.LinkDetails
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_xai_shared_billing_types_proto_init() }
func file_xai_shared_billing_types_proto_init() {
	if File_xai_shared_billing_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xai_shared_billing_types_proto_rawDesc), len(file_xai_shared_billing_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xai_shared_billing_types_proto_goTypes,
		DependencyIndexes: file_xai_shared_billing_types_proto_depIdxs,
		EnumInfos:         file_xai_shared_billing_types_proto_enumTypes,
		MessageInfos:      file_xai_shared_billing_types_proto_msgTypes,
	}.Build()
	File_xai_shared_billing_types_proto = out.File
	file_xai_shared_billing_types_proto_goTypes = nil
	file_xai_shared_billing_types_proto_depIdxs = nil
}
