// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: xai/api/v1/collections.proto

package collectionspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Collections_CreateCollection_FullMethodName             = "/collections.Collections/CreateCollection"
	Collections_ListCollections_FullMethodName              = "/collections.Collections/ListCollections"
	Collections_DeleteCollection_FullMethodName             = "/collections.Collections/DeleteCollection"
	Collections_GetCollectionMetadata_FullMethodName        = "/collections.Collections/GetCollectionMetadata"
	Collections_ListAvailableEmbeddingModels_FullMethodName = "/collections.Collections/ListAvailableEmbeddingModels"
	Collections_ListAvailableTokenEncodings_FullMethodName  = "/collections.Collections/ListAvailableTokenEncodings"
	Collections_UploadDocument_FullMethodName               = "/collections.Collections/UploadDocument"
	Collections_UpdateDocument_FullMethodName               = "/collections.Collections/UpdateDocument"
	Collections_ListDocuments_FullMethodName                = "/collections.Collections/ListDocuments"
	Collections_GetDocumentMetadata_FullMethodName          = "/collections.Collections/GetDocumentMetadata"
	Collections_AddDocumentToCollection_FullMethodName      = "/collections.Collections/AddDocumentToCollection"
	Collections_RemoveDocumentFromCollection_FullMethodName = "/collections.Collections/RemoveDocumentFromCollection"
	Collections_ReIndexDocument_FullMethodName              = "/collections.Collections/ReIndexDocument"
	Collections_UpdateCollection_FullMethodName             = "/collections.Collections/UpdateCollection"
	Collections_BatchGetDocuments_FullMethodName            = "/collections.Collections/BatchGetDocuments"
)

// CollectionsClient is the client API for Collections service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionsClient interface {
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CollectionMetadata, error)
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCollectionMetadata(ctx context.Context, in *GetCollectionMetadataRequest, opts ...grpc.CallOption) (*CollectionMetadata, error)
	ListAvailableEmbeddingModels(ctx context.Context, in *ListAvailableEmbeddingModelsRequest, opts ...grpc.CallOption) (*ListAvailableEmbeddingModelsResponse, error)
	ListAvailableTokenEncodings(ctx context.Context, in *ListAvailableTokenEncodingsRequest, opts ...grpc.CallOption) (*ListAvailableTokenEncodingsResponse, error)
	UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*DocumentMetadata, error)
	UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*DocumentMetadata, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	GetDocumentMetadata(ctx context.Context, in *GetDocumentMetadataRequest, opts ...grpc.CallOption) (*DocumentMetadata, error)
	AddDocumentToCollection(ctx context.Context, in *AddDocumentToCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveDocumentFromCollection(ctx context.Context, in *RemoveDocumentFromCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReIndexDocument(ctx context.Context, in *ReIndexDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCollection(ctx context.Context, in *UpdateCollectionRequest, opts ...grpc.CallOption) (*CollectionMetadata, error)
	BatchGetDocuments(ctx context.Context, in *BatchGetDocumentsRequest, opts ...grpc.CallOption) (*BatchGetDocumentsResponse, error)
}

type collectionsClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionsClient(cc grpc.ClientConnInterface) CollectionsClient {
	return &collectionsClient{cc}
}

func (c *collectionsClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CollectionMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionMetadata)
	err := c.cc.Invoke(ctx, Collections_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, Collections_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Collections_DeleteCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) GetCollectionMetadata(ctx context.Context, in *GetCollectionMetadataRequest, opts ...grpc.CallOption) (*CollectionMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionMetadata)
	err := c.cc.Invoke(ctx, Collections_GetCollectionMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) ListAvailableEmbeddingModels(ctx context.Context, in *ListAvailableEmbeddingModelsRequest, opts ...grpc.CallOption) (*ListAvailableEmbeddingModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableEmbeddingModelsResponse)
	err := c.cc.Invoke(ctx, Collections_ListAvailableEmbeddingModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) ListAvailableTokenEncodings(ctx context.Context, in *ListAvailableTokenEncodingsRequest, opts ...grpc.CallOption) (*ListAvailableTokenEncodingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableTokenEncodingsResponse)
	err := c.cc.Invoke(ctx, Collections_ListAvailableTokenEncodings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*DocumentMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentMetadata)
	err := c.cc.Invoke(ctx, Collections_UploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*DocumentMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentMetadata)
	err := c.cc.Invoke(ctx, Collections_UpdateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, Collections_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) GetDocumentMetadata(ctx context.Context, in *GetDocumentMetadataRequest, opts ...grpc.CallOption) (*DocumentMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentMetadata)
	err := c.cc.Invoke(ctx, Collections_GetDocumentMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) AddDocumentToCollection(ctx context.Context, in *AddDocumentToCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Collections_AddDocumentToCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) RemoveDocumentFromCollection(ctx context.Context, in *RemoveDocumentFromCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Collections_RemoveDocumentFromCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) ReIndexDocument(ctx context.Context, in *ReIndexDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Collections_ReIndexDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) UpdateCollection(ctx context.Context, in *UpdateCollectionRequest, opts ...grpc.CallOption) (*CollectionMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionMetadata)
	err := c.cc.Invoke(ctx, Collections_UpdateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionsClient) BatchGetDocuments(ctx context.Context, in *BatchGetDocumentsRequest, opts ...grpc.CallOption) (*BatchGetDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetDocumentsResponse)
	err := c.cc.Invoke(ctx, Collections_BatchGetDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionsServer is the server API for Collections service.
// All implementations must embed UnimplementedCollectionsServer
// for forward compatibility.
type CollectionsServer interface {
	CreateCollection(context.Context, *CreateCollectionRequest) (*CollectionMetadata, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*emptypb.Empty, error)
	GetCollectionMetadata(context.Context, *GetCollectionMetadataRequest) (*CollectionMetadata, error)
	ListAvailableEmbeddingModels(context.Context, *ListAvailableEmbeddingModelsRequest) (*ListAvailableEmbeddingModelsResponse, error)
	ListAvailableTokenEncodings(context.Context, *ListAvailableTokenEncodingsRequest) (*ListAvailableTokenEncodingsResponse, error)
	UploadDocument(context.Context, *UploadDocumentRequest) (*DocumentMetadata, error)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*DocumentMetadata, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	GetDocumentMetadata(context.Context, *GetDocumentMetadataRequest) (*DocumentMetadata, error)
	AddDocumentToCollection(context.Context, *AddDocumentToCollectionRequest) (*emptypb.Empty, error)
	RemoveDocumentFromCollection(context.Context, *RemoveDocumentFromCollectionRequest) (*emptypb.Empty, error)
	ReIndexDocument(context.Context, *ReIndexDocumentRequest) (*emptypb.Empty, error)
	UpdateCollection(context.Context, *UpdateCollectionRequest) (*CollectionMetadata, error)
	BatchGetDocuments(context.Context, *BatchGetDocumentsRequest) (*BatchGetDocumentsResponse, error)
	mustEmbedUnimplementedCollectionsServer()
}

// UnimplementedCollectionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectionsServer struct{}

func (UnimplementedCollectionsServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CollectionMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedCollectionsServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedCollectionsServer) DeleteCollection(context.Context, *DeleteCollectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedCollectionsServer) GetCollectionMetadata(context.Context, *GetCollectionMetadataRequest) (*CollectionMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionMetadata not implemented")
}
func (UnimplementedCollectionsServer) ListAvailableEmbeddingModels(context.Context, *ListAvailableEmbeddingModelsRequest) (*ListAvailableEmbeddingModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableEmbeddingModels not implemented")
}
func (UnimplementedCollectionsServer) ListAvailableTokenEncodings(context.Context, *ListAvailableTokenEncodingsRequest) (*ListAvailableTokenEncodingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableTokenEncodings not implemented")
}
func (UnimplementedCollectionsServer) UploadDocument(context.Context, *UploadDocumentRequest) (*DocumentMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedCollectionsServer) UpdateDocument(context.Context, *UpdateDocumentRequest) (*DocumentMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocument not implemented")
}
func (UnimplementedCollectionsServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedCollectionsServer) GetDocumentMetadata(context.Context, *GetDocumentMetadataRequest) (*DocumentMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentMetadata not implemented")
}
func (UnimplementedCollectionsServer) AddDocumentToCollection(context.Context, *AddDocumentToCollectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDocumentToCollection not implemented")
}
func (UnimplementedCollectionsServer) RemoveDocumentFromCollection(context.Context, *RemoveDocumentFromCollectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDocumentFromCollection not implemented")
}
func (UnimplementedCollectionsServer) ReIndexDocument(context.Context, *ReIndexDocumentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReIndexDocument not implemented")
}
func (UnimplementedCollectionsServer) UpdateCollection(context.Context, *UpdateCollectionRequest) (*CollectionMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollection not implemented")
}
func (UnimplementedCollectionsServer) BatchGetDocuments(context.Context, *BatchGetDocumentsRequest) (*BatchGetDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetDocuments not implemented")
}
func (UnimplementedCollectionsServer) mustEmbedUnimplementedCollectionsServer() {}
func (UnimplementedCollectionsServer) testEmbeddedByValue()                     {}

// UnsafeCollectionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionsServer will
// result in compilation errors.
type UnsafeCollectionsServer interface {
	mustEmbedUnimplementedCollectionsServer()
}

func RegisterCollectionsServer(s grpc.ServiceRegistrar, srv CollectionsServer) {
	// If the following call pancis, it indicates UnimplementedCollectionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Collections_ServiceDesc, srv)
}

func _Collections_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_GetCollectionMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).GetCollectionMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_GetCollectionMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).GetCollectionMetadata(ctx, req.(*GetCollectionMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_ListAvailableEmbeddingModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableEmbeddingModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).ListAvailableEmbeddingModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_ListAvailableEmbeddingModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).ListAvailableEmbeddingModels(ctx, req.(*ListAvailableEmbeddingModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_ListAvailableTokenEncodings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableTokenEncodingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).ListAvailableTokenEncodings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_ListAvailableTokenEncodings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).ListAvailableTokenEncodings(ctx, req.(*ListAvailableTokenEncodingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_UploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).UploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_UploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).UploadDocument(ctx, req.(*UploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_UpdateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).UpdateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_UpdateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).UpdateDocument(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_GetDocumentMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).GetDocumentMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_GetDocumentMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).GetDocumentMetadata(ctx, req.(*GetDocumentMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_AddDocumentToCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDocumentToCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).AddDocumentToCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_AddDocumentToCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).AddDocumentToCollection(ctx, req.(*AddDocumentToCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_RemoveDocumentFromCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDocumentFromCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).RemoveDocumentFromCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_RemoveDocumentFromCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).RemoveDocumentFromCollection(ctx, req.(*RemoveDocumentFromCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_ReIndexDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReIndexDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).ReIndexDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_ReIndexDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).ReIndexDocument(ctx, req.(*ReIndexDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_UpdateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).UpdateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_UpdateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).UpdateCollection(ctx, req.(*UpdateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collections_BatchGetDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsServer).BatchGetDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collections_BatchGetDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsServer).BatchGetDocuments(ctx, req.(*BatchGetDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Collections_ServiceDesc is the grpc.ServiceDesc for Collections service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collections_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collections.Collections",
	HandlerType: (*CollectionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _Collections_CreateCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _Collections_ListCollections_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _Collections_DeleteCollection_Handler,
		},
		{
			MethodName: "GetCollectionMetadata",
			Handler:    _Collections_GetCollectionMetadata_Handler,
		},
		{
			MethodName: "ListAvailableEmbeddingModels",
			Handler:    _Collections_ListAvailableEmbeddingModels_Handler,
		},
		{
			MethodName: "ListAvailableTokenEncodings",
			Handler:    _Collections_ListAvailableTokenEncodings_Handler,
		},
		{
			MethodName: "UploadDocument",
			Handler:    _Collections_UploadDocument_Handler,
		},
		{
			MethodName: "UpdateDocument",
			Handler:    _Collections_UpdateDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _Collections_ListDocuments_Handler,
		},
		{
			MethodName: "GetDocumentMetadata",
			Handler:    _Collections_GetDocumentMetadata_Handler,
		},
		{
			MethodName: "AddDocumentToCollection",
			Handler:    _Collections_AddDocumentToCollection_Handler,
		},
		{
			MethodName: "RemoveDocumentFromCollection",
			Handler:    _Collections_RemoveDocumentFromCollection_Handler,
		},
		{
			MethodName: "ReIndexDocument",
			Handler:    _Collections_ReIndexDocument_Handler,
		},
		{
			MethodName: "UpdateCollection",
			Handler:    _Collections_UpdateCollection_Handler,
		},
		{
			MethodName: "BatchGetDocuments",
			Handler:    _Collections_BatchGetDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xai/api/v1/collections.proto",
}
