// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: xai/api/v1/sample.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sample_SampleText_FullMethodName          = "/xai_api.Sample/SampleText"
	Sample_SampleTextStreaming_FullMethodName = "/xai_api.Sample/SampleTextStreaming"
)

// SampleClient is the client API for Sample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// An API service for sampling the responses of available language models.
type SampleClient interface {
	// Get raw sampling of text response from the model inference.
	SampleText(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (*SampleTextResponse, error)
	// Get streaming raw sampling of text response from the model inference.
	SampleTextStreaming(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SampleTextResponse], error)
}

type sampleClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleClient(cc grpc.ClientConnInterface) SampleClient {
	return &sampleClient{cc}
}

func (c *sampleClient) SampleText(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (*SampleTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleTextResponse)
	err := c.cc.Invoke(ctx, Sample_SampleText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleClient) SampleTextStreaming(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SampleTextResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sample_ServiceDesc.Streams[0], Sample_SampleTextStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SampleTextRequest, SampleTextResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sample_SampleTextStreamingClient = grpc.ServerStreamingClient[SampleTextResponse]

// SampleServer is the server API for Sample service.
// All implementations must embed UnimplementedSampleServer
// for forward compatibility.
//
// An API service for sampling the responses of available language models.
type SampleServer interface {
	// Get raw sampling of text response from the model inference.
	SampleText(context.Context, *SampleTextRequest) (*SampleTextResponse, error)
	// Get streaming raw sampling of text response from the model inference.
	SampleTextStreaming(*SampleTextRequest, grpc.ServerStreamingServer[SampleTextResponse]) error
	mustEmbedUnimplementedSampleServer()
}

// UnimplementedSampleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSampleServer struct{}

func (UnimplementedSampleServer) SampleText(context.Context, *SampleTextRequest) (*SampleTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SampleText not implemented")
}
func (UnimplementedSampleServer) SampleTextStreaming(*SampleTextRequest, grpc.ServerStreamingServer[SampleTextResponse]) error {
	return status.Error(codes.Unimplemented, "method SampleTextStreaming not implemented")
}
func (UnimplementedSampleServer) mustEmbedUnimplementedSampleServer() {}
func (UnimplementedSampleServer) testEmbeddedByValue()                {}

// UnsafeSampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServer will
// result in compilation errors.
type UnsafeSampleServer interface {
	mustEmbedUnimplementedSampleServer()
}

func RegisterSampleServer(s grpc.ServiceRegistrar, srv SampleServer) {
	// If the following call panics, it indicates UnimplementedSampleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sample_ServiceDesc, srv)
}

func _Sample_SampleText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServer).SampleText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sample_SampleText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServer).SampleText(ctx, req.(*SampleTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sample_SampleTextStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SampleTextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SampleServer).SampleTextStreaming(m, &grpc.GenericServerStream[SampleTextRequest, SampleTextResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sample_SampleTextStreamingServer = grpc.ServerStreamingServer[SampleTextResponse]

// Sample_ServiceDesc is the grpc.ServiceDesc for Sample service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sample_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xai_api.Sample",
	HandlerType: (*SampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SampleText",
			Handler:    _Sample_SampleText_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SampleTextStreaming",
			Handler:       _Sample_SampleTextStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xai/api/v1/sample.proto",
}
