// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: xai/api/v1/tokenize.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tokenize_TokenizeText_FullMethodName = "/xai_api.Tokenize/TokenizeText"
)

// TokenizeClient is the client API for Tokenize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// An API service to tokenize input prompts.
type TokenizeClient interface {
	// Convert text to a sequence of tokens.
	TokenizeText(ctx context.Context, in *TokenizeTextRequest, opts ...grpc.CallOption) (*TokenizeTextResponse, error)
}

type tokenizeClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizeClient(cc grpc.ClientConnInterface) TokenizeClient {
	return &tokenizeClient{cc}
}

func (c *tokenizeClient) TokenizeText(ctx context.Context, in *TokenizeTextRequest, opts ...grpc.CallOption) (*TokenizeTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeTextResponse)
	err := c.cc.Invoke(ctx, Tokenize_TokenizeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenizeServer is the server API for Tokenize service.
// All implementations must embed UnimplementedTokenizeServer
// for forward compatibility.
//
// An API service to tokenize input prompts.
type TokenizeServer interface {
	// Convert text to a sequence of tokens.
	TokenizeText(context.Context, *TokenizeTextRequest) (*TokenizeTextResponse, error)
	mustEmbedUnimplementedTokenizeServer()
}

// UnimplementedTokenizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenizeServer struct{}

func (UnimplementedTokenizeServer) TokenizeText(context.Context, *TokenizeTextRequest) (*TokenizeTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenizeText not implemented")
}
func (UnimplementedTokenizeServer) mustEmbedUnimplementedTokenizeServer() {}
func (UnimplementedTokenizeServer) testEmbeddedByValue()                  {}

// UnsafeTokenizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenizeServer will
// result in compilation errors.
type UnsafeTokenizeServer interface {
	mustEmbedUnimplementedTokenizeServer()
}

func RegisterTokenizeServer(s grpc.ServiceRegistrar, srv TokenizeServer) {
	// If the following call pancis, it indicates UnimplementedTokenizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tokenize_ServiceDesc, srv)
}

func _Tokenize_TokenizeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizeServer).TokenizeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokenize_TokenizeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizeServer).TokenizeText(ctx, req.(*TokenizeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tokenize_ServiceDesc is the grpc.ServiceDesc for Tokenize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tokenize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xai_api.Tokenize",
	HandlerType: (*TokenizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenizeText",
			Handler:    _Tokenize_TokenizeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xai/api/v1/tokenize.proto",
}
